/*
Navicat MySQL Data Transfer

Source Server         : localhsot
Source Server Version : 50520
Source Host           : localhost:3306
Source Database       : appsocial

Target Server Type    : MYSQL
Target Server Version : 50520
File Encoding         : 65001

Date: 2014-08-03 10:23:16
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for base
-- ----------------------------
DROP TABLE IF EXISTS `base`;
CREATE TABLE `base` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created` datetime NOT NULL,
  `createdby` int(11) NOT NULL,
  `modified` datetime DEFAULT NULL,
  `modifiedby` int(11) DEFAULT NULL,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of base
-- ----------------------------

-- ----------------------------
-- Table structure for complaints
-- ----------------------------
DROP TABLE IF EXISTS `complaints`;
CREATE TABLE `complaints` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `tipology_id` int(11) NOT NULL,
  `subtipology_id` int(11) NOT NULL,
  `region_id` varchar(5) COLLATE utf8_unicode_ci NOT NULL,
  `state_id` int(11) NOT NULL,
  `latitude` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `longitude` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `donde` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `que_paso` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `response` text COLLATE utf8_unicode_ci,
  `created` datetime NOT NULL,
  `createdby` int(11) NOT NULL,
  `modified` datetime DEFAULT NULL,
  `modifiedby` int(11) DEFAULT NULL,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `tipology_id` (`tipology_id`),
  KEY `subtipology_id` (`subtipology_id`),
  KEY `region_id` (`region_id`),
  KEY `state_id` (`state_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `complaints_ibfk_1` FOREIGN KEY (`tipology_id`) REFERENCES `tipologies` (`id`),
  CONSTRAINT `complaints_ibfk_2` FOREIGN KEY (`subtipology_id`) REFERENCES `subtipologies` (`id`),
  CONSTRAINT `complaints_ibfk_3` FOREIGN KEY (`region_id`) REFERENCES `regions` (`cod_municipio`),
  CONSTRAINT `complaints_ibfk_4` FOREIGN KEY (`state_id`) REFERENCES `states` (`id`),
  CONSTRAINT `complaints_ibfk_5` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of complaints
-- ----------------------------
INSERT INTO `complaints` VALUES ('2', '1', '1', '1', '11001', '1', '-', '-', 'Lugar', 'Denuncia', 'Respuesta', '2014-08-02 17:43:36', '1', '2014-08-03 05:33:44', null, '0');
INSERT INTO `complaints` VALUES ('3', '2', '1', '1', '05001', '1', '-', '-', 'Lugar', 'Denuncia', 'Respuesta', '2014-08-02 17:43:36', '1', '2014-08-03 05:34:55', null, '0');
INSERT INTO `complaints` VALUES ('4', '2', '1', '1', '05001', '1', '-', '-', 'Lugar', 'Denuncia', 'Respuesta', '2014-08-02 17:43:36', '1', '2014-08-03 05:36:08', null, '0');
INSERT INTO `complaints` VALUES ('5', '2', '1', '1', '11001', '1', '-', '-', 'Lugar', 'Denuncia', 'Respuesta', '2014-08-02 17:43:36', '1', '2014-08-03 05:36:31', null, '0');
INSERT INTO `complaints` VALUES ('6', '2', '1', '1', '11001', '1', '-', '-', 'Lugar', 'Denuncia', 'Respuesta', '2014-08-02 17:43:36', '1', '2014-08-03 05:37:18', null, '0');
INSERT INTO `complaints` VALUES ('7', '2', '1', '1', '11001', '1', '-', '-', 'Lugar', 'Denuncia', 'Respuesta', '2014-08-02 17:43:36', '1', '2014-08-03 05:37:31', null, '0');
INSERT INTO `complaints` VALUES ('8', '2', '1', '1', '11001', '1', '-', '-', 'Lugar', 'Denuncia', 'Respuesta', '2014-08-02 17:43:36', '1', '2014-08-03 05:37:49', null, '0');

-- ----------------------------
-- Table structure for groups
-- ----------------------------
DROP TABLE IF EXISTS `groups`;
CREATE TABLE `groups` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created` datetime NOT NULL,
  `createdby` int(11) NOT NULL,
  `modified` datetime DEFAULT NULL,
  `modifiedby` int(11) DEFAULT NULL,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of groups
-- ----------------------------
INSERT INTO `groups` VALUES ('1', 'Funcionarios Personeria', '2014-08-02 17:42:08', '1', '0000-00-00 00:00:00', '0', '0');
INSERT INTO `groups` VALUES ('2', 'Ciudadano', '2014-08-02 17:42:49', '1', '0000-00-00 00:00:00', '0', '0');

-- ----------------------------
-- Table structure for regions
-- ----------------------------
DROP TABLE IF EXISTS `regions`;
CREATE TABLE `regions` (
  `cod_departamento` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `cod_municipio` varchar(5) COLLATE utf8_unicode_ci NOT NULL,
  `nombre_departamento` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `nombre_municipio` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  KEY `cod_municipio` (`cod_municipio`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of regions
-- ----------------------------
INSERT INTO `regions` VALUES ('05', '05001', 'ANTIOQUIA', 'MEDELLIN');
INSERT INTO `regions` VALUES ('05', '05002', 'ANTIOQUIA', 'ABEJORRAL');
INSERT INTO `regions` VALUES ('05', '05004', 'ANTIOQUIA', 'ABRIAQUI');
INSERT INTO `regions` VALUES ('05', '05021', 'ANTIOQUIA', 'ALEJANDRIA');
INSERT INTO `regions` VALUES ('05', '05030', 'ANTIOQUIA', 'AMAGA');
INSERT INTO `regions` VALUES ('05', '05031', 'ANTIOQUIA', 'AMALFI');
INSERT INTO `regions` VALUES ('05', '05034', 'ANTIOQUIA', 'ANDES');
INSERT INTO `regions` VALUES ('05', '05036', 'ANTIOQUIA', 'ANGELOPOLIS');
INSERT INTO `regions` VALUES ('05', '05038', 'ANTIOQUIA', 'ANGOSTURA');
INSERT INTO `regions` VALUES ('05', '05040', 'ANTIOQUIA', 'ANORI');
INSERT INTO `regions` VALUES ('05', '05042', 'ANTIOQUIA', 'SANTAFE DE ANTIOQUIA');
INSERT INTO `regions` VALUES ('05', '05044', 'ANTIOQUIA', 'ANZA');
INSERT INTO `regions` VALUES ('05', '05045', 'ANTIOQUIA', 'APARTADO');
INSERT INTO `regions` VALUES ('05', '05051', 'ANTIOQUIA', 'ARBOLETES');
INSERT INTO `regions` VALUES ('05', '05055', 'ANTIOQUIA', 'ARGELIA');
INSERT INTO `regions` VALUES ('05', '05059', 'ANTIOQUIA', 'ARMENIA');
INSERT INTO `regions` VALUES ('05', '05079', 'ANTIOQUIA', 'BARBOSA');
INSERT INTO `regions` VALUES ('05', '05086', 'ANTIOQUIA', 'BELMIRA');
INSERT INTO `regions` VALUES ('05', '05088', 'ANTIOQUIA', 'BELLO');
INSERT INTO `regions` VALUES ('05', '05091', 'ANTIOQUIA', 'BETANIA');
INSERT INTO `regions` VALUES ('05', '05093', 'ANTIOQUIA', 'BETULIA');
INSERT INTO `regions` VALUES ('05', '05101', 'ANTIOQUIA', 'CIUDAD BOLIVAR');
INSERT INTO `regions` VALUES ('05', '05107', 'ANTIOQUIA', 'BRICEÑO');
INSERT INTO `regions` VALUES ('05', '05113', 'ANTIOQUIA', 'BURITICA');
INSERT INTO `regions` VALUES ('05', '05120', 'ANTIOQUIA', 'CACERES');
INSERT INTO `regions` VALUES ('05', '05125', 'ANTIOQUIA', 'CAICEDO');
INSERT INTO `regions` VALUES ('05', '05129', 'ANTIOQUIA', 'CALDAS');
INSERT INTO `regions` VALUES ('05', '05134', 'ANTIOQUIA', 'CAMPAMENTO');
INSERT INTO `regions` VALUES ('05', '05138', 'ANTIOQUIA', 'CAÑASGORDAS');
INSERT INTO `regions` VALUES ('05', '05142', 'ANTIOQUIA', 'CARACOLI');
INSERT INTO `regions` VALUES ('05', '05145', 'ANTIOQUIA', 'CARAMANTA');
INSERT INTO `regions` VALUES ('05', '05147', 'ANTIOQUIA', 'CAREPA');
INSERT INTO `regions` VALUES ('05', '05148', 'ANTIOQUIA', 'CARMEN DE VIBORAL');
INSERT INTO `regions` VALUES ('05', '05150', 'ANTIOQUIA', 'CAROLINA');
INSERT INTO `regions` VALUES ('05', '05154', 'ANTIOQUIA', 'CAUCASIA');
INSERT INTO `regions` VALUES ('05', '05172', 'ANTIOQUIA', 'CHIGORODO');
INSERT INTO `regions` VALUES ('05', '05190', 'ANTIOQUIA', 'CISNEROS');
INSERT INTO `regions` VALUES ('05', '05197', 'ANTIOQUIA', 'COCORNA');
INSERT INTO `regions` VALUES ('05', '05206', 'ANTIOQUIA', 'CONCEPCION');
INSERT INTO `regions` VALUES ('05', '05209', 'ANTIOQUIA', 'CONCORDIA');
INSERT INTO `regions` VALUES ('05', '05212', 'ANTIOQUIA', 'COPACABANA');
INSERT INTO `regions` VALUES ('05', '05234', 'ANTIOQUIA', 'DABEIBA');
INSERT INTO `regions` VALUES ('05', '05237', 'ANTIOQUIA', 'DON MATIAS');
INSERT INTO `regions` VALUES ('05', '05240', 'ANTIOQUIA', 'EBEJICO');
INSERT INTO `regions` VALUES ('05', '05250', 'ANTIOQUIA', 'EL BAGRE');
INSERT INTO `regions` VALUES ('05', '05264', 'ANTIOQUIA', 'ENTRERRIOS');
INSERT INTO `regions` VALUES ('05', '05266', 'ANTIOQUIA', 'ENVIGADO');
INSERT INTO `regions` VALUES ('05', '05282', 'ANTIOQUIA', 'FREDONIA');
INSERT INTO `regions` VALUES ('05', '05284', 'ANTIOQUIA', 'FRONTINO');
INSERT INTO `regions` VALUES ('05', '05306', 'ANTIOQUIA', 'GIRALDO');
INSERT INTO `regions` VALUES ('05', '05308', 'ANTIOQUIA', 'GIRARDOTA');
INSERT INTO `regions` VALUES ('05', '05310', 'ANTIOQUIA', 'GOMEZ PLATA');
INSERT INTO `regions` VALUES ('05', '05313', 'ANTIOQUIA', 'GRANADA');
INSERT INTO `regions` VALUES ('05', '05315', 'ANTIOQUIA', 'GUADALUPE');
INSERT INTO `regions` VALUES ('05', '05318', 'ANTIOQUIA', 'GUARNE');
INSERT INTO `regions` VALUES ('05', '05321', 'ANTIOQUIA', 'GUATAPE');
INSERT INTO `regions` VALUES ('05', '05347', 'ANTIOQUIA', 'HELICONIA');
INSERT INTO `regions` VALUES ('05', '05353', 'ANTIOQUIA', 'HISPANIA');
INSERT INTO `regions` VALUES ('05', '05360', 'ANTIOQUIA', 'ITAGUI');
INSERT INTO `regions` VALUES ('05', '05361', 'ANTIOQUIA', 'ITUANGO');
INSERT INTO `regions` VALUES ('05', '05364', 'ANTIOQUIA', 'JARDIN');
INSERT INTO `regions` VALUES ('05', '05368', 'ANTIOQUIA', 'JERICO');
INSERT INTO `regions` VALUES ('05', '05376', 'ANTIOQUIA', 'LA CEJA');
INSERT INTO `regions` VALUES ('05', '05380', 'ANTIOQUIA', 'LA ESTRELLA');
INSERT INTO `regions` VALUES ('05', '05390', 'ANTIOQUIA', 'LA PINTADA');
INSERT INTO `regions` VALUES ('05', '05400', 'ANTIOQUIA', 'LA UNION');
INSERT INTO `regions` VALUES ('05', '05411', 'ANTIOQUIA', 'LIBORINA');
INSERT INTO `regions` VALUES ('05', '05425', 'ANTIOQUIA', 'MACEO');
INSERT INTO `regions` VALUES ('05', '05440', 'ANTIOQUIA', 'MARINILLA');
INSERT INTO `regions` VALUES ('05', '05467', 'ANTIOQUIA', 'MONTEBELLO');
INSERT INTO `regions` VALUES ('05', '05475', 'ANTIOQUIA', 'MURINDO');
INSERT INTO `regions` VALUES ('05', '05480', 'ANTIOQUIA', 'MUTATA');
INSERT INTO `regions` VALUES ('05', '05483', 'ANTIOQUIA', 'NARIÑO');
INSERT INTO `regions` VALUES ('05', '05490', 'ANTIOQUIA', 'NECOCLI');
INSERT INTO `regions` VALUES ('05', '05495', 'ANTIOQUIA', 'NECHI');
INSERT INTO `regions` VALUES ('05', '05501', 'ANTIOQUIA', 'OLAYA');
INSERT INTO `regions` VALUES ('05', '05541', 'ANTIOQUIA', 'PEÑOL');
INSERT INTO `regions` VALUES ('05', '05543', 'ANTIOQUIA', 'PEQUE');
INSERT INTO `regions` VALUES ('05', '05576', 'ANTIOQUIA', 'PUEBLORRICO');
INSERT INTO `regions` VALUES ('05', '05579', 'ANTIOQUIA', 'PUERTO BERRIO');
INSERT INTO `regions` VALUES ('05', '05585', 'ANTIOQUIA', 'PUERTO NARE');
INSERT INTO `regions` VALUES ('05', '05591', 'ANTIOQUIA', 'PUERTO TRIUNFO');
INSERT INTO `regions` VALUES ('05', '05604', 'ANTIOQUIA', 'REMEDIOS');
INSERT INTO `regions` VALUES ('05', '05607', 'ANTIOQUIA', 'RETIRO');
INSERT INTO `regions` VALUES ('05', '05615', 'ANTIOQUIA', 'RIONEGRO');
INSERT INTO `regions` VALUES ('05', '05628', 'ANTIOQUIA', 'SABANALARGA');
INSERT INTO `regions` VALUES ('05', '05631', 'ANTIOQUIA', 'SABANETA');
INSERT INTO `regions` VALUES ('05', '05642', 'ANTIOQUIA', 'SALGAR');
INSERT INTO `regions` VALUES ('05', '05647', 'ANTIOQUIA', 'SAN ANDRES');
INSERT INTO `regions` VALUES ('05', '05649', 'ANTIOQUIA', 'SAN CARLOS');
INSERT INTO `regions` VALUES ('05', '05652', 'ANTIOQUIA', 'SAN FRANCISCO');
INSERT INTO `regions` VALUES ('05', '05656', 'ANTIOQUIA', 'SAN JERONIMO');
INSERT INTO `regions` VALUES ('05', '05658', 'ANTIOQUIA', 'SAN JOSE DE LA MONTAÑA');
INSERT INTO `regions` VALUES ('05', '05659', 'ANTIOQUIA', 'SAN JUAN DE URABA');
INSERT INTO `regions` VALUES ('05', '05660', 'ANTIOQUIA', 'SAN LUIS');
INSERT INTO `regions` VALUES ('05', '05664', 'ANTIOQUIA', 'SAN PEDRO');
INSERT INTO `regions` VALUES ('05', '05665', 'ANTIOQUIA', 'SAN PEDRO DE URABA');
INSERT INTO `regions` VALUES ('05', '05667', 'ANTIOQUIA', 'SAN RAFAEL');
INSERT INTO `regions` VALUES ('05', '05670', 'ANTIOQUIA', 'SAN ROQUE');
INSERT INTO `regions` VALUES ('05', '05674', 'ANTIOQUIA', 'SAN VICENTE');
INSERT INTO `regions` VALUES ('05', '05679', 'ANTIOQUIA', 'SANTA BARBARA');
INSERT INTO `regions` VALUES ('05', '05686', 'ANTIOQUIA', 'SANTA ROSA DE OSOS');
INSERT INTO `regions` VALUES ('05', '05690', 'ANTIOQUIA', 'SANTO DOMINGO');
INSERT INTO `regions` VALUES ('05', '05697', 'ANTIOQUIA', 'SANTUARIO');
INSERT INTO `regions` VALUES ('05', '05736', 'ANTIOQUIA', 'SEGOVIA');
INSERT INTO `regions` VALUES ('05', '05756', 'ANTIOQUIA', 'SONSON');
INSERT INTO `regions` VALUES ('05', '05761', 'ANTIOQUIA', 'SOPETRAN');
INSERT INTO `regions` VALUES ('05', '05789', 'ANTIOQUIA', 'TAMESIS');
INSERT INTO `regions` VALUES ('05', '05790', 'ANTIOQUIA', 'TARAZA');
INSERT INTO `regions` VALUES ('05', '05792', 'ANTIOQUIA', 'TARSO');
INSERT INTO `regions` VALUES ('05', '05809', 'ANTIOQUIA', 'TITIRIBI');
INSERT INTO `regions` VALUES ('05', '05819', 'ANTIOQUIA', 'TOLEDO');
INSERT INTO `regions` VALUES ('05', '05837', 'ANTIOQUIA', 'TURBO');
INSERT INTO `regions` VALUES ('05', '05842', 'ANTIOQUIA', 'URAMITA');
INSERT INTO `regions` VALUES ('05', '05847', 'ANTIOQUIA', 'URRAO');
INSERT INTO `regions` VALUES ('05', '05854', 'ANTIOQUIA', 'VALDIVIA');
INSERT INTO `regions` VALUES ('05', '05856', 'ANTIOQUIA', 'VALPARAISO');
INSERT INTO `regions` VALUES ('05', '05858', 'ANTIOQUIA', 'VEGACHI');
INSERT INTO `regions` VALUES ('05', '05861', 'ANTIOQUIA', 'VENECIA');
INSERT INTO `regions` VALUES ('05', '05873', 'ANTIOQUIA', 'VIGIA DEL FUERTE');
INSERT INTO `regions` VALUES ('05', '05885', 'ANTIOQUIA', 'YALI');
INSERT INTO `regions` VALUES ('05', '05887', 'ANTIOQUIA', 'YARUMAL');
INSERT INTO `regions` VALUES ('05', '05890', 'ANTIOQUIA', 'YOLOMBO');
INSERT INTO `regions` VALUES ('05', '05893', 'ANTIOQUIA', 'YONDO');
INSERT INTO `regions` VALUES ('05', '05895', 'ANTIOQUIA', 'ZARAGOZA');
INSERT INTO `regions` VALUES ('08', '08001', 'ATLÁNTICO', 'BARRANQUILLA');
INSERT INTO `regions` VALUES ('08', '08078', 'ATLÁNTICO', 'BARANOA');
INSERT INTO `regions` VALUES ('08', '08137', 'ATLÁNTICO', 'CAMPO DE LA CRUZ');
INSERT INTO `regions` VALUES ('08', '08141', 'ATLÁNTICO', 'CANDELARIA');
INSERT INTO `regions` VALUES ('08', '08296', 'ATLÁNTICO', 'GALAPA');
INSERT INTO `regions` VALUES ('08', '08372', 'ATLÁNTICO', 'JUAN DE ACOSTA');
INSERT INTO `regions` VALUES ('08', '08421', 'ATLÁNTICO', 'LURUACO');
INSERT INTO `regions` VALUES ('08', '08433', 'ATLÁNTICO', 'MALAMBO');
INSERT INTO `regions` VALUES ('08', '08436', 'ATLÁNTICO', 'MANATI');
INSERT INTO `regions` VALUES ('08', '08520', 'ATLÁNTICO', 'PALMAR DE VARELA');
INSERT INTO `regions` VALUES ('08', '08549', 'ATLÁNTICO', 'PIOJO');
INSERT INTO `regions` VALUES ('08', '08558', 'ATLÁNTICO', 'POLONUEVO');
INSERT INTO `regions` VALUES ('08', '08560', 'ATLÁNTICO', 'PONEDERA');
INSERT INTO `regions` VALUES ('08', '08573', 'ATLÁNTICO', 'PUERTO COLOMBIA');
INSERT INTO `regions` VALUES ('08', '08606', 'ATLÁNTICO', 'REPELON');
INSERT INTO `regions` VALUES ('08', '08634', 'ATLÁNTICO', 'SABANAGRANDE');
INSERT INTO `regions` VALUES ('08', '08638', 'ATLÁNTICO', 'SABANALARGA');
INSERT INTO `regions` VALUES ('08', '08675', 'ATLÁNTICO', 'SANTA LUCIA');
INSERT INTO `regions` VALUES ('08', '08685', 'ATLÁNTICO', 'SANTO TOMAS');
INSERT INTO `regions` VALUES ('08', '08758', 'ATLÁNTICO', 'SOLEDAD');
INSERT INTO `regions` VALUES ('08', '08770', 'ATLÁNTICO', 'SUAN');
INSERT INTO `regions` VALUES ('08', '08832', 'ATLÁNTICO', 'TUBARA');
INSERT INTO `regions` VALUES ('08', '08849', 'ATLÁNTICO', 'USIACURI');
INSERT INTO `regions` VALUES ('11', '11001', 'BOGOTÁ, D. C.', 'BOGOTA D.C.');
INSERT INTO `regions` VALUES ('13', '13001', 'BOLÍVAR', 'CARTAGENA');
INSERT INTO `regions` VALUES ('13', '13006', 'BOLÍVAR', 'ACHI');
INSERT INTO `regions` VALUES ('13', '13030', 'BOLÍVAR', 'ALTOS DEL ROSARIO');
INSERT INTO `regions` VALUES ('13', '13042', 'BOLÍVAR', 'ARENAL');
INSERT INTO `regions` VALUES ('13', '13052', 'BOLÍVAR', 'ARJONA');
INSERT INTO `regions` VALUES ('13', '13062', 'BOLÍVAR', 'ARROYOHONDO');
INSERT INTO `regions` VALUES ('13', '13074', 'BOLÍVAR', 'BARRANCO DE LOBA');
INSERT INTO `regions` VALUES ('13', '13140', 'BOLÍVAR', 'CALAMAR');
INSERT INTO `regions` VALUES ('13', '13160', 'BOLÍVAR', 'CANTAGALLO');
INSERT INTO `regions` VALUES ('13', '13188', 'BOLÍVAR', 'CICUCO');
INSERT INTO `regions` VALUES ('13', '13212', 'BOLÍVAR', 'CORDOBA');
INSERT INTO `regions` VALUES ('13', '13222', 'BOLÍVAR', 'CLEMENCIA');
INSERT INTO `regions` VALUES ('13', '13244', 'BOLÍVAR', 'EL CARMEN DE BOLIVAR');
INSERT INTO `regions` VALUES ('13', '13248', 'BOLÍVAR', 'EL GUAMO');
INSERT INTO `regions` VALUES ('13', '13268', 'BOLÍVAR', 'EL PEÑON');
INSERT INTO `regions` VALUES ('13', '13300', 'BOLÍVAR', 'HATILLO DE LOBA');
INSERT INTO `regions` VALUES ('13', '13430', 'BOLÍVAR', 'MAGANGUE');
INSERT INTO `regions` VALUES ('13', '13433', 'BOLÍVAR', 'MAHATES');
INSERT INTO `regions` VALUES ('13', '13440', 'BOLÍVAR', 'MARGARITA');
INSERT INTO `regions` VALUES ('13', '13442', 'BOLÍVAR', 'MARIA LA BAJA');
INSERT INTO `regions` VALUES ('13', '13458', 'BOLÍVAR', 'MONTECRISTO');
INSERT INTO `regions` VALUES ('13', '13468', 'BOLÍVAR', 'MOMPOS');
INSERT INTO `regions` VALUES ('13', '13473', 'BOLÍVAR', 'MORALES');
INSERT INTO `regions` VALUES ('13', '13490', 'BOLÍVAR', 'NOROSI');
INSERT INTO `regions` VALUES ('13', '13549', 'BOLÍVAR', 'PINILLOS');
INSERT INTO `regions` VALUES ('13', '13580', 'BOLÍVAR', 'REGIDOR');
INSERT INTO `regions` VALUES ('13', '13600', 'BOLÍVAR', 'RIO VIEJO');
INSERT INTO `regions` VALUES ('13', '13620', 'BOLÍVAR', 'SAN CRISTOBAL');
INSERT INTO `regions` VALUES ('13', '13647', 'BOLÍVAR', 'SAN ESTANISLAO');
INSERT INTO `regions` VALUES ('13', '13650', 'BOLÍVAR', 'SAN FERNANDO');
INSERT INTO `regions` VALUES ('13', '13654', 'BOLÍVAR', 'SAN JACINTO');
INSERT INTO `regions` VALUES ('13', '13655', 'BOLÍVAR', 'SAN JACINTO DEL CAUCA');
INSERT INTO `regions` VALUES ('13', '13657', 'BOLÍVAR', 'SAN JUAN NEPOMUCENO');
INSERT INTO `regions` VALUES ('13', '13667', 'BOLÍVAR', 'SAN MARTIN DE LOBA');
INSERT INTO `regions` VALUES ('13', '13670', 'BOLÍVAR', 'SAN PABLO');
INSERT INTO `regions` VALUES ('13', '13673', 'BOLÍVAR', 'SANTA CATALINA');
INSERT INTO `regions` VALUES ('13', '13683', 'BOLÍVAR', 'SANTA ROSA');
INSERT INTO `regions` VALUES ('13', '13688', 'BOLÍVAR', 'SANTA ROSA DEL SUR');
INSERT INTO `regions` VALUES ('13', '13744', 'BOLÍVAR', 'SIMITI');
INSERT INTO `regions` VALUES ('13', '13760', 'BOLÍVAR', 'SOPLAVIENTO');
INSERT INTO `regions` VALUES ('13', '13780', 'BOLÍVAR', 'TALAIGUA NUEVO');
INSERT INTO `regions` VALUES ('13', '13810', 'BOLÍVAR', 'TIQUISIO');
INSERT INTO `regions` VALUES ('13', '13836', 'BOLÍVAR', 'TURBACO');
INSERT INTO `regions` VALUES ('13', '13838', 'BOLÍVAR', 'TURBANA');
INSERT INTO `regions` VALUES ('13', '13873', 'BOLÍVAR', 'VILLANUEVA');
INSERT INTO `regions` VALUES ('13', '13894', 'BOLÍVAR', 'ZAMBRANO');
INSERT INTO `regions` VALUES ('15', '15001', 'BOYACÁ', 'TUNJA');
INSERT INTO `regions` VALUES ('15', '15022', 'BOYACÁ', 'ALMEIDA');
INSERT INTO `regions` VALUES ('15', '15047', 'BOYACÁ', 'AQUITANIA');
INSERT INTO `regions` VALUES ('15', '15051', 'BOYACÁ', 'ARCABUCO');
INSERT INTO `regions` VALUES ('15', '15087', 'BOYACÁ', 'BELEN');
INSERT INTO `regions` VALUES ('15', '15090', 'BOYACÁ', 'BERBEO');
INSERT INTO `regions` VALUES ('15', '15092', 'BOYACÁ', 'BETEITIVA');
INSERT INTO `regions` VALUES ('15', '15097', 'BOYACÁ', 'BOAVITA');
INSERT INTO `regions` VALUES ('15', '15104', 'BOYACÁ', 'BOYACA');
INSERT INTO `regions` VALUES ('15', '15106', 'BOYACÁ', 'BRICEÑO');
INSERT INTO `regions` VALUES ('15', '15109', 'BOYACÁ', 'BUENAVISTA');
INSERT INTO `regions` VALUES ('15', '15114', 'BOYACÁ', 'BUSBANZA');
INSERT INTO `regions` VALUES ('15', '15131', 'BOYACÁ', 'CALDAS');
INSERT INTO `regions` VALUES ('15', '15135', 'BOYACÁ', 'CAMPOHERMOSO');
INSERT INTO `regions` VALUES ('15', '15162', 'BOYACÁ', 'CERINZA');
INSERT INTO `regions` VALUES ('15', '15172', 'BOYACÁ', 'CHINAVITA');
INSERT INTO `regions` VALUES ('15', '15176', 'BOYACÁ', 'CHIQUINQUIRA');
INSERT INTO `regions` VALUES ('15', '15180', 'BOYACÁ', 'CHISCAS');
INSERT INTO `regions` VALUES ('15', '15183', 'BOYACÁ', 'CHITA');
INSERT INTO `regions` VALUES ('15', '15185', 'BOYACÁ', 'CHITARAQUE');
INSERT INTO `regions` VALUES ('15', '15187', 'BOYACÁ', 'CHIVATA');
INSERT INTO `regions` VALUES ('15', '15189', 'BOYACÁ', 'CIENEGA');
INSERT INTO `regions` VALUES ('15', '15204', 'BOYACÁ', 'COMBITA');
INSERT INTO `regions` VALUES ('15', '15212', 'BOYACÁ', 'COPER');
INSERT INTO `regions` VALUES ('15', '15215', 'BOYACÁ', 'CORRALES');
INSERT INTO `regions` VALUES ('15', '15218', 'BOYACÁ', 'COVARACHIA');
INSERT INTO `regions` VALUES ('15', '15223', 'BOYACÁ', 'CUBARA');
INSERT INTO `regions` VALUES ('15', '15224', 'BOYACÁ', 'CUCAITA');
INSERT INTO `regions` VALUES ('15', '15226', 'BOYACÁ', 'CUITIVA');
INSERT INTO `regions` VALUES ('15', '15232', 'BOYACÁ', 'CHIQUIZA');
INSERT INTO `regions` VALUES ('15', '15236', 'BOYACÁ', 'CHIVOR');
INSERT INTO `regions` VALUES ('15', '15238', 'BOYACÁ', 'DUITAMA');
INSERT INTO `regions` VALUES ('15', '15244', 'BOYACÁ', 'EL COCUY');
INSERT INTO `regions` VALUES ('15', '15248', 'BOYACÁ', 'EL ESPINO');
INSERT INTO `regions` VALUES ('15', '15272', 'BOYACÁ', 'FIRAVITOBA');
INSERT INTO `regions` VALUES ('15', '15276', 'BOYACÁ', 'FLORESTA');
INSERT INTO `regions` VALUES ('15', '15293', 'BOYACÁ', 'GACHANTIVA');
INSERT INTO `regions` VALUES ('15', '15296', 'BOYACÁ', 'GAMEZA');
INSERT INTO `regions` VALUES ('15', '15299', 'BOYACÁ', 'GARAGOA');
INSERT INTO `regions` VALUES ('15', '15317', 'BOYACÁ', 'GUACAMAYAS');
INSERT INTO `regions` VALUES ('15', '15322', 'BOYACÁ', 'GUATEQUE');
INSERT INTO `regions` VALUES ('15', '15325', 'BOYACÁ', 'GUAYATA');
INSERT INTO `regions` VALUES ('15', '15332', 'BOYACÁ', 'GUICAN');
INSERT INTO `regions` VALUES ('15', '15362', 'BOYACÁ', 'IZA');
INSERT INTO `regions` VALUES ('15', '15367', 'BOYACÁ', 'JENESANO');
INSERT INTO `regions` VALUES ('15', '15368', 'BOYACÁ', 'JERICO');
INSERT INTO `regions` VALUES ('15', '15377', 'BOYACÁ', 'LABRANZAGRANDE');
INSERT INTO `regions` VALUES ('15', '15380', 'BOYACÁ', 'LA CAPILLA');
INSERT INTO `regions` VALUES ('15', '15401', 'BOYACÁ', 'LA VICTORIA');
INSERT INTO `regions` VALUES ('15', '15403', 'BOYACÁ', 'LA UVITA');
INSERT INTO `regions` VALUES ('15', '15407', 'BOYACÁ', 'VILLA DE LEYVA');
INSERT INTO `regions` VALUES ('15', '15425', 'BOYACÁ', 'MACANAL');
INSERT INTO `regions` VALUES ('15', '15442', 'BOYACÁ', 'MARIPI');
INSERT INTO `regions` VALUES ('15', '15455', 'BOYACÁ', 'MIRAFLORES');
INSERT INTO `regions` VALUES ('15', '15464', 'BOYACÁ', 'MONGUA');
INSERT INTO `regions` VALUES ('15', '15466', 'BOYACÁ', 'MONGUI');
INSERT INTO `regions` VALUES ('15', '15469', 'BOYACÁ', 'MONIQUIRA');
INSERT INTO `regions` VALUES ('15', '15476', 'BOYACÁ', 'MOTAVITA');
INSERT INTO `regions` VALUES ('15', '15480', 'BOYACÁ', 'MUZO');
INSERT INTO `regions` VALUES ('15', '15491', 'BOYACÁ', 'NOBSA');
INSERT INTO `regions` VALUES ('15', '15494', 'BOYACÁ', 'NUEVO COLON');
INSERT INTO `regions` VALUES ('15', '15500', 'BOYACÁ', 'OICATA');
INSERT INTO `regions` VALUES ('15', '15507', 'BOYACÁ', 'OTANCHE');
INSERT INTO `regions` VALUES ('15', '15511', 'BOYACÁ', 'PACHAVITA');
INSERT INTO `regions` VALUES ('15', '15514', 'BOYACÁ', 'PAEZ');
INSERT INTO `regions` VALUES ('15', '15516', 'BOYACÁ', 'PAIPA');
INSERT INTO `regions` VALUES ('15', '15518', 'BOYACÁ', 'PAJARITO');
INSERT INTO `regions` VALUES ('15', '15522', 'BOYACÁ', 'PANQUEBA');
INSERT INTO `regions` VALUES ('15', '15531', 'BOYACÁ', 'PAUNA');
INSERT INTO `regions` VALUES ('15', '15533', 'BOYACÁ', 'PAYA');
INSERT INTO `regions` VALUES ('15', '15537', 'BOYACÁ', 'PAZ DE RIO');
INSERT INTO `regions` VALUES ('15', '15542', 'BOYACÁ', 'PESCA');
INSERT INTO `regions` VALUES ('15', '15550', 'BOYACÁ', 'PISBA');
INSERT INTO `regions` VALUES ('15', '15572', 'BOYACÁ', 'PUERTO BOYACA');
INSERT INTO `regions` VALUES ('15', '15580', 'BOYACÁ', 'QUIPAMA');
INSERT INTO `regions` VALUES ('15', '15599', 'BOYACÁ', 'RAMIRIQUI');
INSERT INTO `regions` VALUES ('15', '15600', 'BOYACÁ', 'RAQUIRA');
INSERT INTO `regions` VALUES ('15', '15621', 'BOYACÁ', 'RONDON');
INSERT INTO `regions` VALUES ('15', '15632', 'BOYACÁ', 'SABOYA');
INSERT INTO `regions` VALUES ('15', '15638', 'BOYACÁ', 'SACHICA');
INSERT INTO `regions` VALUES ('15', '15646', 'BOYACÁ', 'SAMACA');
INSERT INTO `regions` VALUES ('15', '15660', 'BOYACÁ', 'SAN EDUARDO');
INSERT INTO `regions` VALUES ('15', '15664', 'BOYACÁ', 'SAN JOSE DE PARE');
INSERT INTO `regions` VALUES ('15', '15667', 'BOYACÁ', 'SAN LUIS DE GACENO');
INSERT INTO `regions` VALUES ('15', '15673', 'BOYACÁ', 'SAN MATEO');
INSERT INTO `regions` VALUES ('15', '15676', 'BOYACÁ', 'SAN MIGUEL DE SEMA');
INSERT INTO `regions` VALUES ('15', '15681', 'BOYACÁ', 'SAN PABLO BORBUR');
INSERT INTO `regions` VALUES ('15', '15686', 'BOYACÁ', 'SANTANA');
INSERT INTO `regions` VALUES ('15', '15690', 'BOYACÁ', 'SANTA MARIA');
INSERT INTO `regions` VALUES ('15', '15693', 'BOYACÁ', 'SAN ROSA VITERBO');
INSERT INTO `regions` VALUES ('15', '15696', 'BOYACÁ', 'SANTA SOFIA');
INSERT INTO `regions` VALUES ('15', '15720', 'BOYACÁ', 'SATIVANORTE');
INSERT INTO `regions` VALUES ('15', '15723', 'BOYACÁ', 'SATIVASUR');
INSERT INTO `regions` VALUES ('15', '15740', 'BOYACÁ', 'SIACHOQUE');
INSERT INTO `regions` VALUES ('15', '15753', 'BOYACÁ', 'SOATA');
INSERT INTO `regions` VALUES ('15', '15755', 'BOYACÁ', 'SOCOTA');
INSERT INTO `regions` VALUES ('15', '15757', 'BOYACÁ', 'SOCHA');
INSERT INTO `regions` VALUES ('15', '15759', 'BOYACÁ', 'SOGAMOSO');
INSERT INTO `regions` VALUES ('15', '15761', 'BOYACÁ', 'SOMONDOCO');
INSERT INTO `regions` VALUES ('15', '15762', 'BOYACÁ', 'SORA');
INSERT INTO `regions` VALUES ('15', '15763', 'BOYACÁ', 'SOTAQUIRA');
INSERT INTO `regions` VALUES ('15', '15764', 'BOYACÁ', 'SORACA');
INSERT INTO `regions` VALUES ('15', '15774', 'BOYACÁ', 'SUSACON');
INSERT INTO `regions` VALUES ('15', '15776', 'BOYACÁ', 'SUTAMARCHAN');
INSERT INTO `regions` VALUES ('15', '15778', 'BOYACÁ', 'SUTATENZA');
INSERT INTO `regions` VALUES ('15', '15790', 'BOYACÁ', 'TASCO');
INSERT INTO `regions` VALUES ('15', '15798', 'BOYACÁ', 'TENZA');
INSERT INTO `regions` VALUES ('15', '15804', 'BOYACÁ', 'TIBANA');
INSERT INTO `regions` VALUES ('15', '15806', 'BOYACÁ', 'TIBASOSA');
INSERT INTO `regions` VALUES ('15', '15808', 'BOYACÁ', 'TINJACA');
INSERT INTO `regions` VALUES ('15', '15810', 'BOYACÁ', 'TIPACOQUE');
INSERT INTO `regions` VALUES ('15', '15814', 'BOYACÁ', 'TOCA');
INSERT INTO `regions` VALUES ('15', '15816', 'BOYACÁ', 'TOGUI');
INSERT INTO `regions` VALUES ('15', '15820', 'BOYACÁ', 'TOPAGA');
INSERT INTO `regions` VALUES ('15', '15822', 'BOYACÁ', 'TOTA');
INSERT INTO `regions` VALUES ('15', '15832', 'BOYACÁ', 'TUNUNGUA');
INSERT INTO `regions` VALUES ('15', '15835', 'BOYACÁ', 'TURMEQUE');
INSERT INTO `regions` VALUES ('15', '15837', 'BOYACÁ', 'TUTA');
INSERT INTO `regions` VALUES ('15', '15839', 'BOYACÁ', 'TUTAZA');
INSERT INTO `regions` VALUES ('15', '15842', 'BOYACÁ', 'UMBITA');
INSERT INTO `regions` VALUES ('15', '15861', 'BOYACÁ', 'VENTAQUEMADA');
INSERT INTO `regions` VALUES ('15', '15879', 'BOYACÁ', 'VIRACACHA');
INSERT INTO `regions` VALUES ('15', '15897', 'BOYACÁ', 'ZETAQUIRA');
INSERT INTO `regions` VALUES ('17', '17001', 'CALDAS', 'MANIZALES');
INSERT INTO `regions` VALUES ('17', '17013', 'CALDAS', 'AGUADAS');
INSERT INTO `regions` VALUES ('17', '17042', 'CALDAS', 'ANSERMA');
INSERT INTO `regions` VALUES ('17', '17050', 'CALDAS', 'ARANZAZU');
INSERT INTO `regions` VALUES ('17', '17088', 'CALDAS', 'BELALCAZAR');
INSERT INTO `regions` VALUES ('17', '17174', 'CALDAS', 'CHINCHINA');
INSERT INTO `regions` VALUES ('17', '17272', 'CALDAS', 'FILADELFIA');
INSERT INTO `regions` VALUES ('17', '17380', 'CALDAS', 'LA DORADA');
INSERT INTO `regions` VALUES ('17', '17388', 'CALDAS', 'LA MERCED');
INSERT INTO `regions` VALUES ('17', '17433', 'CALDAS', 'MANZANARES');
INSERT INTO `regions` VALUES ('17', '17442', 'CALDAS', 'MARMATO');
INSERT INTO `regions` VALUES ('17', '17444', 'CALDAS', 'MARQUETALIA');
INSERT INTO `regions` VALUES ('17', '17446', 'CALDAS', 'MARULANDA');
INSERT INTO `regions` VALUES ('17', '17486', 'CALDAS', 'NEIRA');
INSERT INTO `regions` VALUES ('17', '17495', 'CALDAS', 'NORCASIA');
INSERT INTO `regions` VALUES ('17', '17513', 'CALDAS', 'PACORA');
INSERT INTO `regions` VALUES ('17', '17524', 'CALDAS', 'PALESTINA');
INSERT INTO `regions` VALUES ('17', '17541', 'CALDAS', 'PENSILVANIA');
INSERT INTO `regions` VALUES ('17', '17614', 'CALDAS', 'RIOSUCIO');
INSERT INTO `regions` VALUES ('17', '17616', 'CALDAS', 'RISARALDA');
INSERT INTO `regions` VALUES ('17', '17653', 'CALDAS', 'SALAMINA');
INSERT INTO `regions` VALUES ('17', '17662', 'CALDAS', 'SAMANA');
INSERT INTO `regions` VALUES ('17', '17665', 'CALDAS', 'SAN JOSE');
INSERT INTO `regions` VALUES ('17', '17777', 'CALDAS', 'SUPIA');
INSERT INTO `regions` VALUES ('17', '17867', 'CALDAS', 'VICTORIA');
INSERT INTO `regions` VALUES ('17', '17873', 'CALDAS', 'VILLAMARIA');
INSERT INTO `regions` VALUES ('17', '17877', 'CALDAS', 'VITERBO');
INSERT INTO `regions` VALUES ('18', '18001', 'CAQUETÁ', 'FLORENCIA');
INSERT INTO `regions` VALUES ('18', '18029', 'CAQUETÁ', 'ALBANIA');
INSERT INTO `regions` VALUES ('18', '18094', 'CAQUETÁ', 'BELEN DE LOS ANDAQUIES');
INSERT INTO `regions` VALUES ('18', '18150', 'CAQUETÁ', 'CARTAGENA DEL CHAIRA');
INSERT INTO `regions` VALUES ('18', '18205', 'CAQUETÁ', 'CURRILLO');
INSERT INTO `regions` VALUES ('18', '18247', 'CAQUETÁ', 'EL DONCELLO');
INSERT INTO `regions` VALUES ('18', '18256', 'CAQUETÁ', 'EL PAUJIL');
INSERT INTO `regions` VALUES ('18', '18410', 'CAQUETÁ', 'LA MONTAÑITA');
INSERT INTO `regions` VALUES ('18', '18460', 'CAQUETÁ', 'MILAN');
INSERT INTO `regions` VALUES ('18', '18479', 'CAQUETÁ', 'MORELIA');
INSERT INTO `regions` VALUES ('18', '18592', 'CAQUETÁ', 'PUERTO RICO');
INSERT INTO `regions` VALUES ('18', '18610', 'CAQUETÁ', 'SAN JOSE DEL FRAGUA');
INSERT INTO `regions` VALUES ('18', '18753', 'CAQUETÁ', 'SAN VICENTE DEL CAGUAN');
INSERT INTO `regions` VALUES ('18', '18756', 'CAQUETÁ', 'SOLANO');
INSERT INTO `regions` VALUES ('18', '18785', 'CAQUETÁ', 'SOLITA');
INSERT INTO `regions` VALUES ('18', '18860', 'CAQUETÁ', 'VALPARAISO');
INSERT INTO `regions` VALUES ('19', '19001', 'CAUCA', 'POPAYAN');
INSERT INTO `regions` VALUES ('19', '19022', 'CAUCA', 'ALMAGUER');
INSERT INTO `regions` VALUES ('19', '19050', 'CAUCA', 'ARGELIA');
INSERT INTO `regions` VALUES ('19', '19075', 'CAUCA', 'BALBOA');
INSERT INTO `regions` VALUES ('19', '19100', 'CAUCA', 'BOLIVAR');
INSERT INTO `regions` VALUES ('19', '19110', 'CAUCA', 'BUENOS AIRES');
INSERT INTO `regions` VALUES ('19', '19130', 'CAUCA', 'CAJIBIO');
INSERT INTO `regions` VALUES ('19', '19137', 'CAUCA', 'CALDONO');
INSERT INTO `regions` VALUES ('19', '19142', 'CAUCA', 'CALOTO');
INSERT INTO `regions` VALUES ('19', '19212', 'CAUCA', 'CORINTO');
INSERT INTO `regions` VALUES ('19', '19256', 'CAUCA', 'EL TAMBO');
INSERT INTO `regions` VALUES ('19', '19290', 'CAUCA', 'FLORENCIA');
INSERT INTO `regions` VALUES ('19', '19300', 'CAUCA', 'GUACHENE');
INSERT INTO `regions` VALUES ('19', '19318', 'CAUCA', 'GUAPI');
INSERT INTO `regions` VALUES ('19', '19355', 'CAUCA', 'INZA');
INSERT INTO `regions` VALUES ('19', '19364', 'CAUCA', 'JAMBALO');
INSERT INTO `regions` VALUES ('19', '19392', 'CAUCA', 'LA SIERRA');
INSERT INTO `regions` VALUES ('19', '19397', 'CAUCA', 'LA VEGA');
INSERT INTO `regions` VALUES ('19', '19418', 'CAUCA', 'LOPEZ');
INSERT INTO `regions` VALUES ('19', '19450', 'CAUCA', 'MERCADERES');
INSERT INTO `regions` VALUES ('19', '19455', 'CAUCA', 'MIRANDA');
INSERT INTO `regions` VALUES ('19', '19473', 'CAUCA', 'MORALES');
INSERT INTO `regions` VALUES ('19', '19513', 'CAUCA', 'PADILLA');
INSERT INTO `regions` VALUES ('19', '19517', 'CAUCA', 'PAEZ');
INSERT INTO `regions` VALUES ('19', '19532', 'CAUCA', 'PATIA');
INSERT INTO `regions` VALUES ('19', '19533', 'CAUCA', 'PIAMONTE');
INSERT INTO `regions` VALUES ('19', '19548', 'CAUCA', 'PIENDAMO');
INSERT INTO `regions` VALUES ('19', '19573', 'CAUCA', 'PUERTO TEJADA');
INSERT INTO `regions` VALUES ('19', '19585', 'CAUCA', 'PURACE');
INSERT INTO `regions` VALUES ('19', '19622', 'CAUCA', 'ROSAS');
INSERT INTO `regions` VALUES ('19', '19693', 'CAUCA', 'SAN SEBASTIAN');
INSERT INTO `regions` VALUES ('19', '19698', 'CAUCA', 'SANTANDER DE QUILICHAO');
INSERT INTO `regions` VALUES ('19', '19701', 'CAUCA', 'SANTA ROSA');
INSERT INTO `regions` VALUES ('19', '19743', 'CAUCA', 'SILVIA');
INSERT INTO `regions` VALUES ('19', '19760', 'CAUCA', 'SOTARA');
INSERT INTO `regions` VALUES ('19', '19780', 'CAUCA', 'SUAREZ');
INSERT INTO `regions` VALUES ('19', '19785', 'CAUCA', 'SUCRE');
INSERT INTO `regions` VALUES ('19', '19807', 'CAUCA', 'TIMBIO');
INSERT INTO `regions` VALUES ('19', '19809', 'CAUCA', 'TIMBIQUI');
INSERT INTO `regions` VALUES ('19', '19821', 'CAUCA', 'TORIBIO');
INSERT INTO `regions` VALUES ('19', '19824', 'CAUCA', 'TOTORO');
INSERT INTO `regions` VALUES ('19', '19845', 'CAUCA', 'VILLA RICA');
INSERT INTO `regions` VALUES ('20', '20001', 'CESAR', 'VALLEDUPAR');
INSERT INTO `regions` VALUES ('20', '20011', 'CESAR', 'AGUACHICA');
INSERT INTO `regions` VALUES ('20', '20013', 'CESAR', 'AGUSTIN CODAZZI');
INSERT INTO `regions` VALUES ('20', '20032', 'CESAR', 'ASTREA');
INSERT INTO `regions` VALUES ('20', '20045', 'CESAR', 'BECERRIL');
INSERT INTO `regions` VALUES ('20', '20060', 'CESAR', 'BOSCONIA');
INSERT INTO `regions` VALUES ('20', '20175', 'CESAR', 'CHIMICHAGUA');
INSERT INTO `regions` VALUES ('20', '20178', 'CESAR', 'CHIRIGUANA');
INSERT INTO `regions` VALUES ('20', '20228', 'CESAR', 'CURUMANI');
INSERT INTO `regions` VALUES ('20', '20238', 'CESAR', 'EL COPEY');
INSERT INTO `regions` VALUES ('20', '20250', 'CESAR', 'EL PASO');
INSERT INTO `regions` VALUES ('20', '20295', 'CESAR', 'GAMARRA');
INSERT INTO `regions` VALUES ('20', '20310', 'CESAR', 'GONZALEZ');
INSERT INTO `regions` VALUES ('20', '20383', 'CESAR', 'LA GLORIA');
INSERT INTO `regions` VALUES ('20', '20400', 'CESAR', 'LA JAGUA DE IBIRICO');
INSERT INTO `regions` VALUES ('20', '20443', 'CESAR', 'MANAURE');
INSERT INTO `regions` VALUES ('20', '20517', 'CESAR', 'PAILITAS');
INSERT INTO `regions` VALUES ('20', '20550', 'CESAR', 'PELAYA');
INSERT INTO `regions` VALUES ('20', '20570', 'CESAR', 'PUEBLO BELLO');
INSERT INTO `regions` VALUES ('20', '20614', 'CESAR', 'RIO DE ORO');
INSERT INTO `regions` VALUES ('20', '20621', 'CESAR', 'LA PAZ');
INSERT INTO `regions` VALUES ('20', '20710', 'CESAR', 'SAN ALBERTO');
INSERT INTO `regions` VALUES ('20', '20750', 'CESAR', 'SAN DIEGO');
INSERT INTO `regions` VALUES ('20', '20770', 'CESAR', 'SAN MARTIN');
INSERT INTO `regions` VALUES ('20', '20787', 'CESAR', 'TAMALAMEQUE');
INSERT INTO `regions` VALUES ('23', '23001', 'CÓRDOBA', 'MONTERIA');
INSERT INTO `regions` VALUES ('23', '23068', 'CÓRDOBA', 'AYAPEL');
INSERT INTO `regions` VALUES ('23', '23079', 'CÓRDOBA', 'BUENAVISTA');
INSERT INTO `regions` VALUES ('23', '23090', 'CÓRDOBA', 'CANALETE');
INSERT INTO `regions` VALUES ('23', '23162', 'CÓRDOBA', 'CERETE');
INSERT INTO `regions` VALUES ('23', '23168', 'CÓRDOBA', 'CHIMA');
INSERT INTO `regions` VALUES ('23', '23182', 'CÓRDOBA', 'CHINU');
INSERT INTO `regions` VALUES ('23', '23189', 'CÓRDOBA', 'CIENAGA DE ORO');
INSERT INTO `regions` VALUES ('23', '23300', 'CÓRDOBA', 'COTORRA');
INSERT INTO `regions` VALUES ('23', '23350', 'CÓRDOBA', 'LA APARTADA');
INSERT INTO `regions` VALUES ('23', '23417', 'CÓRDOBA', 'LORICA');
INSERT INTO `regions` VALUES ('23', '23419', 'CÓRDOBA', 'LOS CORDOBAS');
INSERT INTO `regions` VALUES ('23', '23464', 'CÓRDOBA', 'MOMIL');
INSERT INTO `regions` VALUES ('23', '23466', 'CÓRDOBA', 'MONTELIBANO');
INSERT INTO `regions` VALUES ('23', '23500', 'CÓRDOBA', 'MOÑITOS');
INSERT INTO `regions` VALUES ('23', '23555', 'CÓRDOBA', 'PLANETA RICA');
INSERT INTO `regions` VALUES ('23', '23570', 'CÓRDOBA', 'PUEBLO NUEVO');
INSERT INTO `regions` VALUES ('23', '23574', 'CÓRDOBA', 'PUERTO ESCONDIDO');
INSERT INTO `regions` VALUES ('23', '23580', 'CÓRDOBA', 'PUERTO LIBERTADOR');
INSERT INTO `regions` VALUES ('23', '23586', 'CÓRDOBA', 'PURISIMA');
INSERT INTO `regions` VALUES ('23', '23660', 'CÓRDOBA', 'SAHAGUN');
INSERT INTO `regions` VALUES ('23', '23670', 'CÓRDOBA', 'SAN ANDRES SOTAVENTO');
INSERT INTO `regions` VALUES ('23', '23672', 'CÓRDOBA', 'SAN ANTERO');
INSERT INTO `regions` VALUES ('23', '23675', 'CÓRDOBA', 'SAN BERNARDO DEL VIENTO');
INSERT INTO `regions` VALUES ('23', '23678', 'CÓRDOBA', 'SAN CARLOS');
INSERT INTO `regions` VALUES ('23', '23682', 'CÓRDOBA', 'SAN JOSE DE URE');
INSERT INTO `regions` VALUES ('23', '23686', 'CÓRDOBA', 'SAN PELAYO');
INSERT INTO `regions` VALUES ('23', '23807', 'CÓRDOBA', 'TIERRALTA');
INSERT INTO `regions` VALUES ('23', '23815', 'CÓRDOBA', 'TUCHIN');
INSERT INTO `regions` VALUES ('23', '23855', 'CÓRDOBA', 'VALENCIA');
INSERT INTO `regions` VALUES ('25', '25001', 'CUNDINAMARCA', 'AGUA DE DIOS');
INSERT INTO `regions` VALUES ('25', '25019', 'CUNDINAMARCA', 'ALBAN');
INSERT INTO `regions` VALUES ('25', '25035', 'CUNDINAMARCA', 'ANAPOIMA');
INSERT INTO `regions` VALUES ('25', '25040', 'CUNDINAMARCA', 'ANOLAIMA');
INSERT INTO `regions` VALUES ('25', '25053', 'CUNDINAMARCA', 'ARBELAEZ');
INSERT INTO `regions` VALUES ('25', '25086', 'CUNDINAMARCA', 'BELTRAN');
INSERT INTO `regions` VALUES ('25', '25095', 'CUNDINAMARCA', 'BITUIMA');
INSERT INTO `regions` VALUES ('25', '25099', 'CUNDINAMARCA', 'BOJACA');
INSERT INTO `regions` VALUES ('25', '25120', 'CUNDINAMARCA', 'CABRERA');
INSERT INTO `regions` VALUES ('25', '25123', 'CUNDINAMARCA', 'CACHIPAY');
INSERT INTO `regions` VALUES ('25', '25126', 'CUNDINAMARCA', 'CAJICA');
INSERT INTO `regions` VALUES ('25', '25148', 'CUNDINAMARCA', 'CAPARRAPI');
INSERT INTO `regions` VALUES ('25', '25151', 'CUNDINAMARCA', 'CAQUEZA');
INSERT INTO `regions` VALUES ('25', '25154', 'CUNDINAMARCA', 'CARMEN DE CARUPA');
INSERT INTO `regions` VALUES ('25', '25168', 'CUNDINAMARCA', 'CHAGUANI');
INSERT INTO `regions` VALUES ('25', '25175', 'CUNDINAMARCA', 'CHIA');
INSERT INTO `regions` VALUES ('25', '25178', 'CUNDINAMARCA', 'CHIPAQUE');
INSERT INTO `regions` VALUES ('25', '25181', 'CUNDINAMARCA', 'CHOACHI');
INSERT INTO `regions` VALUES ('25', '25183', 'CUNDINAMARCA', 'CHOCONTA');
INSERT INTO `regions` VALUES ('25', '25200', 'CUNDINAMARCA', 'COGUA');
INSERT INTO `regions` VALUES ('25', '25214', 'CUNDINAMARCA', 'COTA');
INSERT INTO `regions` VALUES ('25', '25224', 'CUNDINAMARCA', 'CUCUNUBA');
INSERT INTO `regions` VALUES ('25', '25245', 'CUNDINAMARCA', 'EL COLEGIO');
INSERT INTO `regions` VALUES ('25', '25258', 'CUNDINAMARCA', 'EL PEÑON');
INSERT INTO `regions` VALUES ('25', '25260', 'CUNDINAMARCA', 'EL ROSAL');
INSERT INTO `regions` VALUES ('25', '25269', 'CUNDINAMARCA', 'FACATATIVA');
INSERT INTO `regions` VALUES ('25', '25279', 'CUNDINAMARCA', 'FOMEQUE');
INSERT INTO `regions` VALUES ('25', '25281', 'CUNDINAMARCA', 'FOSCA');
INSERT INTO `regions` VALUES ('25', '25286', 'CUNDINAMARCA', 'FUNZA');
INSERT INTO `regions` VALUES ('25', '25288', 'CUNDINAMARCA', 'FUQUENE');
INSERT INTO `regions` VALUES ('25', '25290', 'CUNDINAMARCA', 'FUSAGASUGA');
INSERT INTO `regions` VALUES ('25', '25293', 'CUNDINAMARCA', 'GACHALA');
INSERT INTO `regions` VALUES ('25', '25295', 'CUNDINAMARCA', 'GACHANCIPA');
INSERT INTO `regions` VALUES ('25', '25297', 'CUNDINAMARCA', 'GACHETA');
INSERT INTO `regions` VALUES ('25', '25299', 'CUNDINAMARCA', 'GAMA');
INSERT INTO `regions` VALUES ('25', '25307', 'CUNDINAMARCA', 'GIRARDOT');
INSERT INTO `regions` VALUES ('25', '25312', 'CUNDINAMARCA', 'GRANADA');
INSERT INTO `regions` VALUES ('25', '25317', 'CUNDINAMARCA', 'GUACHETA');
INSERT INTO `regions` VALUES ('25', '25320', 'CUNDINAMARCA', 'GUADUAS');
INSERT INTO `regions` VALUES ('25', '25322', 'CUNDINAMARCA', 'GUASCA');
INSERT INTO `regions` VALUES ('25', '25324', 'CUNDINAMARCA', 'GUATAQUI');
INSERT INTO `regions` VALUES ('25', '25326', 'CUNDINAMARCA', 'GUATAVITA');
INSERT INTO `regions` VALUES ('25', '25328', 'CUNDINAMARCA', 'GUAYABAL DE SIQUIMA');
INSERT INTO `regions` VALUES ('25', '25335', 'CUNDINAMARCA', 'GUAYABETAL');
INSERT INTO `regions` VALUES ('25', '25339', 'CUNDINAMARCA', 'GUTIERREZ');
INSERT INTO `regions` VALUES ('25', '25368', 'CUNDINAMARCA', 'JERUSALEN');
INSERT INTO `regions` VALUES ('25', '25372', 'CUNDINAMARCA', 'JUNIN');
INSERT INTO `regions` VALUES ('25', '25377', 'CUNDINAMARCA', 'LA CALERA');
INSERT INTO `regions` VALUES ('25', '25386', 'CUNDINAMARCA', 'LA MESA');
INSERT INTO `regions` VALUES ('25', '25394', 'CUNDINAMARCA', 'LA PALMA');
INSERT INTO `regions` VALUES ('25', '25398', 'CUNDINAMARCA', 'LA PEÑA');
INSERT INTO `regions` VALUES ('25', '25402', 'CUNDINAMARCA', 'LA VEGA');
INSERT INTO `regions` VALUES ('25', '25407', 'CUNDINAMARCA', 'LENGUAZAQUE');
INSERT INTO `regions` VALUES ('25', '25426', 'CUNDINAMARCA', 'MACHETA');
INSERT INTO `regions` VALUES ('25', '25430', 'CUNDINAMARCA', 'MADRID');
INSERT INTO `regions` VALUES ('25', '25436', 'CUNDINAMARCA', 'MANTA');
INSERT INTO `regions` VALUES ('25', '25438', 'CUNDINAMARCA', 'MEDINA');
INSERT INTO `regions` VALUES ('25', '25473', 'CUNDINAMARCA', 'MOSQUERA');
INSERT INTO `regions` VALUES ('25', '25483', 'CUNDINAMARCA', 'NARIÑO');
INSERT INTO `regions` VALUES ('25', '25486', 'CUNDINAMARCA', 'NEMOCON');
INSERT INTO `regions` VALUES ('25', '25488', 'CUNDINAMARCA', 'NILO');
INSERT INTO `regions` VALUES ('25', '25489', 'CUNDINAMARCA', 'NIMAIMA');
INSERT INTO `regions` VALUES ('25', '25491', 'CUNDINAMARCA', 'NOCAIMA');
INSERT INTO `regions` VALUES ('25', '25506', 'CUNDINAMARCA', 'VENECIA');
INSERT INTO `regions` VALUES ('25', '25513', 'CUNDINAMARCA', 'PACHO');
INSERT INTO `regions` VALUES ('25', '25518', 'CUNDINAMARCA', 'PAIME');
INSERT INTO `regions` VALUES ('25', '25524', 'CUNDINAMARCA', 'PANDI');
INSERT INTO `regions` VALUES ('25', '25530', 'CUNDINAMARCA', 'PARATEBUENO');
INSERT INTO `regions` VALUES ('25', '25535', 'CUNDINAMARCA', 'PASCA');
INSERT INTO `regions` VALUES ('25', '25572', 'CUNDINAMARCA', 'PUERTO SALGAR');
INSERT INTO `regions` VALUES ('25', '25580', 'CUNDINAMARCA', 'PULI');
INSERT INTO `regions` VALUES ('25', '25592', 'CUNDINAMARCA', 'QUEBRADANEGRA');
INSERT INTO `regions` VALUES ('25', '25594', 'CUNDINAMARCA', 'QUETAME');
INSERT INTO `regions` VALUES ('25', '25596', 'CUNDINAMARCA', 'QUIPILE');
INSERT INTO `regions` VALUES ('25', '25599', 'CUNDINAMARCA', 'APULO');
INSERT INTO `regions` VALUES ('25', '25612', 'CUNDINAMARCA', 'RICAURTE');
INSERT INTO `regions` VALUES ('25', '25645', 'CUNDINAMARCA', 'SAN ANTONIO DE TEQUENDAMA');
INSERT INTO `regions` VALUES ('25', '25649', 'CUNDINAMARCA', 'SAN BERNARDO');
INSERT INTO `regions` VALUES ('25', '25653', 'CUNDINAMARCA', 'SAN CAYETANO');
INSERT INTO `regions` VALUES ('25', '25658', 'CUNDINAMARCA', 'SAN FRANCISCO');
INSERT INTO `regions` VALUES ('25', '25662', 'CUNDINAMARCA', 'SAN JUAN DE RIO SECO');
INSERT INTO `regions` VALUES ('25', '25718', 'CUNDINAMARCA', 'SASAIMA');
INSERT INTO `regions` VALUES ('25', '25736', 'CUNDINAMARCA', 'SESQUILE');
INSERT INTO `regions` VALUES ('25', '25740', 'CUNDINAMARCA', 'SIBATE');
INSERT INTO `regions` VALUES ('25', '25743', 'CUNDINAMARCA', 'SILVANIA');
INSERT INTO `regions` VALUES ('25', '25745', 'CUNDINAMARCA', 'SIMIJACA');
INSERT INTO `regions` VALUES ('25', '25754', 'CUNDINAMARCA', 'SOACHA');
INSERT INTO `regions` VALUES ('25', '25758', 'CUNDINAMARCA', 'SOPO');
INSERT INTO `regions` VALUES ('25', '25769', 'CUNDINAMARCA', 'SUBACHOQUE');
INSERT INTO `regions` VALUES ('25', '25772', 'CUNDINAMARCA', 'SUESCA');
INSERT INTO `regions` VALUES ('25', '25777', 'CUNDINAMARCA', 'SUPATA');
INSERT INTO `regions` VALUES ('25', '25779', 'CUNDINAMARCA', 'SUSA');
INSERT INTO `regions` VALUES ('25', '25781', 'CUNDINAMARCA', 'SUTATAUSA');
INSERT INTO `regions` VALUES ('25', '25785', 'CUNDINAMARCA', 'TABIO');
INSERT INTO `regions` VALUES ('25', '25793', 'CUNDINAMARCA', 'TAUSA');
INSERT INTO `regions` VALUES ('25', '25797', 'CUNDINAMARCA', 'TENA');
INSERT INTO `regions` VALUES ('25', '25799', 'CUNDINAMARCA', 'TENJO');
INSERT INTO `regions` VALUES ('25', '25805', 'CUNDINAMARCA', 'TIBACUY');
INSERT INTO `regions` VALUES ('25', '25807', 'CUNDINAMARCA', 'TIBIRITA');
INSERT INTO `regions` VALUES ('25', '25815', 'CUNDINAMARCA', 'TOCAIMA');
INSERT INTO `regions` VALUES ('25', '25817', 'CUNDINAMARCA', 'TOCANCIPA');
INSERT INTO `regions` VALUES ('25', '25823', 'CUNDINAMARCA', 'TOPAIPI');
INSERT INTO `regions` VALUES ('25', '25839', 'CUNDINAMARCA', 'UBALA');
INSERT INTO `regions` VALUES ('25', '25841', 'CUNDINAMARCA', 'UBAQUE');
INSERT INTO `regions` VALUES ('25', '25843', 'CUNDINAMARCA', 'UBATE');
INSERT INTO `regions` VALUES ('25', '25845', 'CUNDINAMARCA', 'UNE');
INSERT INTO `regions` VALUES ('25', '25851', 'CUNDINAMARCA', 'UTICA');
INSERT INTO `regions` VALUES ('25', '25862', 'CUNDINAMARCA', 'VERGARA');
INSERT INTO `regions` VALUES ('25', '25867', 'CUNDINAMARCA', 'VIANI');
INSERT INTO `regions` VALUES ('25', '25871', 'CUNDINAMARCA', 'VILLAGOMEZ');
INSERT INTO `regions` VALUES ('25', '25873', 'CUNDINAMARCA', 'VILLAPINZON');
INSERT INTO `regions` VALUES ('25', '25875', 'CUNDINAMARCA', 'VILLETA');
INSERT INTO `regions` VALUES ('25', '25878', 'CUNDINAMARCA', 'VIOTA');
INSERT INTO `regions` VALUES ('25', '25885', 'CUNDINAMARCA', 'YACOPI');
INSERT INTO `regions` VALUES ('25', '25898', 'CUNDINAMARCA', 'ZIPACON');
INSERT INTO `regions` VALUES ('25', '25899', 'CUNDINAMARCA', 'ZIPAQUIRA');
INSERT INTO `regions` VALUES ('27', '27001', 'CHOCÓ', 'QUIBDO');
INSERT INTO `regions` VALUES ('27', '27006', 'CHOCÓ', 'ACANDI');
INSERT INTO `regions` VALUES ('27', '27025', 'CHOCÓ', 'ALTO BAUDO');
INSERT INTO `regions` VALUES ('27', '27050', 'CHOCÓ', 'ATRATO');
INSERT INTO `regions` VALUES ('27', '27073', 'CHOCÓ', 'BAGADO');
INSERT INTO `regions` VALUES ('27', '27075', 'CHOCÓ', 'BAHIA SOLANO');
INSERT INTO `regions` VALUES ('27', '27077', 'CHOCÓ', 'BAJO BAUDO');
INSERT INTO `regions` VALUES ('27', '27099', 'CHOCÓ', 'BOJAYA');
INSERT INTO `regions` VALUES ('27', '27135', 'CHOCÓ', 'CANTON DE SAN PABLO');
INSERT INTO `regions` VALUES ('27', '27150', 'CHOCÓ', 'CARMEN DEL DARIEN');
INSERT INTO `regions` VALUES ('27', '27160', 'CHOCÓ', 'CERTEGUI');
INSERT INTO `regions` VALUES ('27', '27205', 'CHOCÓ', 'CONDOTO');
INSERT INTO `regions` VALUES ('27', '27245', 'CHOCÓ', 'EL CARMEN DE ATRATO');
INSERT INTO `regions` VALUES ('27', '27250', 'CHOCÓ', 'EL LITORAL DEL SAN JUAN');
INSERT INTO `regions` VALUES ('27', '27361', 'CHOCÓ', 'ITSMINA');
INSERT INTO `regions` VALUES ('27', '27372', 'CHOCÓ', 'JURADO');
INSERT INTO `regions` VALUES ('27', '27413', 'CHOCÓ', 'LLORO');
INSERT INTO `regions` VALUES ('27', '27425', 'CHOCÓ', 'MEDIO ATRATO');
INSERT INTO `regions` VALUES ('27', '27430', 'CHOCÓ', 'MEDIO BAUDÓ');
INSERT INTO `regions` VALUES ('27', '27450', 'CHOCÓ', 'MEDIO SAN JUAN');
INSERT INTO `regions` VALUES ('27', '27491', 'CHOCÓ', 'NOVITA');
INSERT INTO `regions` VALUES ('27', '27495', 'CHOCÓ', 'NUQUI');
INSERT INTO `regions` VALUES ('27', '27580', 'CHOCÓ', 'RIO IRO');
INSERT INTO `regions` VALUES ('27', '27600', 'CHOCÓ', 'RIO QUITO');
INSERT INTO `regions` VALUES ('27', '27615', 'CHOCÓ', 'RIOSUCIO');
INSERT INTO `regions` VALUES ('27', '27660', 'CHOCÓ', 'SAN JOSE DEL PALMAR');
INSERT INTO `regions` VALUES ('27', '27745', 'CHOCÓ', 'SIPI');
INSERT INTO `regions` VALUES ('27', '27787', 'CHOCÓ', 'TADO');
INSERT INTO `regions` VALUES ('27', '27800', 'CHOCÓ', 'UNGUIA');
INSERT INTO `regions` VALUES ('27', '27810', 'CHOCÓ', 'UNION PANAMERICANA');
INSERT INTO `regions` VALUES ('41', '41001', 'HUILA', 'NEIVA');
INSERT INTO `regions` VALUES ('41', '41006', 'HUILA', 'ACEVEDO');
INSERT INTO `regions` VALUES ('41', '41013', 'HUILA', 'AGRADO');
INSERT INTO `regions` VALUES ('41', '41016', 'HUILA', 'AIPE');
INSERT INTO `regions` VALUES ('41', '41020', 'HUILA', 'ALGECIRAS');
INSERT INTO `regions` VALUES ('41', '41026', 'HUILA', 'ALTAMIRA');
INSERT INTO `regions` VALUES ('41', '41078', 'HUILA', 'BARAYA');
INSERT INTO `regions` VALUES ('41', '41132', 'HUILA', 'CAMPOALEGRE');
INSERT INTO `regions` VALUES ('41', '41206', 'HUILA', 'COLOMBIA');
INSERT INTO `regions` VALUES ('41', '41244', 'HUILA', 'ELIAS');
INSERT INTO `regions` VALUES ('41', '41298', 'HUILA', 'GARZON');
INSERT INTO `regions` VALUES ('41', '41306', 'HUILA', 'GIGANTE');
INSERT INTO `regions` VALUES ('41', '41319', 'HUILA', 'GUADALUPE');
INSERT INTO `regions` VALUES ('41', '41349', 'HUILA', 'HOBO');
INSERT INTO `regions` VALUES ('41', '41357', 'HUILA', 'IQUIRA');
INSERT INTO `regions` VALUES ('41', '41359', 'HUILA', 'ISNOS');
INSERT INTO `regions` VALUES ('41', '41378', 'HUILA', 'LA ARGENTINA');
INSERT INTO `regions` VALUES ('41', '41396', 'HUILA', 'LA PLATA');
INSERT INTO `regions` VALUES ('41', '41483', 'HUILA', 'NATAGA');
INSERT INTO `regions` VALUES ('41', '41503', 'HUILA', 'OPORAPA');
INSERT INTO `regions` VALUES ('41', '41518', 'HUILA', 'PAICOL');
INSERT INTO `regions` VALUES ('41', '41524', 'HUILA', 'PALERMO');
INSERT INTO `regions` VALUES ('41', '41530', 'HUILA', 'PALESTINA');
INSERT INTO `regions` VALUES ('41', '41548', 'HUILA', 'PITAL');
INSERT INTO `regions` VALUES ('41', '41551', 'HUILA', 'PITALITO');
INSERT INTO `regions` VALUES ('41', '41615', 'HUILA', 'RIVERA');
INSERT INTO `regions` VALUES ('41', '41660', 'HUILA', 'SALADOBLANCO');
INSERT INTO `regions` VALUES ('41', '41668', 'HUILA', 'SAN AGUSTIN');
INSERT INTO `regions` VALUES ('41', '41676', 'HUILA', 'SANTA MARIA');
INSERT INTO `regions` VALUES ('41', '41770', 'HUILA', 'SUAZA');
INSERT INTO `regions` VALUES ('41', '41791', 'HUILA', 'TARQUI');
INSERT INTO `regions` VALUES ('41', '41797', 'HUILA', 'TESALIA');
INSERT INTO `regions` VALUES ('41', '41799', 'HUILA', 'TELLO');
INSERT INTO `regions` VALUES ('41', '41801', 'HUILA', 'TERUEL');
INSERT INTO `regions` VALUES ('41', '41807', 'HUILA', 'TIMANA');
INSERT INTO `regions` VALUES ('41', '41872', 'HUILA', 'VILLAVIEJA');
INSERT INTO `regions` VALUES ('41', '41885', 'HUILA', 'YAGUARA');
INSERT INTO `regions` VALUES ('44', '44001', 'LA GUAJIRA', 'RIOHACHA');
INSERT INTO `regions` VALUES ('44', '44035', 'LA GUAJIRA', 'ALBANIA');
INSERT INTO `regions` VALUES ('44', '44078', 'LA GUAJIRA', 'BARRANCAS');
INSERT INTO `regions` VALUES ('44', '44090', 'LA GUAJIRA', 'DIBULLA');
INSERT INTO `regions` VALUES ('44', '44098', 'LA GUAJIRA', 'DISTRACCION');
INSERT INTO `regions` VALUES ('44', '44110', 'LA GUAJIRA', 'EL MOLINO');
INSERT INTO `regions` VALUES ('44', '44279', 'LA GUAJIRA', 'FONSECA');
INSERT INTO `regions` VALUES ('44', '44378', 'LA GUAJIRA', 'HATONUEVO');
INSERT INTO `regions` VALUES ('44', '44420', 'LA GUAJIRA', 'LA JAGUA DEL PILAR');
INSERT INTO `regions` VALUES ('44', '44430', 'LA GUAJIRA', 'MAICAO');
INSERT INTO `regions` VALUES ('44', '44560', 'LA GUAJIRA', 'MANAURE');
INSERT INTO `regions` VALUES ('44', '44650', 'LA GUAJIRA', 'SAN JUAN DEL CESAR');
INSERT INTO `regions` VALUES ('44', '44847', 'LA GUAJIRA', 'URIBIA');
INSERT INTO `regions` VALUES ('44', '44855', 'LA GUAJIRA', 'URUMITA');
INSERT INTO `regions` VALUES ('44', '44874', 'LA GUAJIRA', 'VILLANUEVA');
INSERT INTO `regions` VALUES ('47', '47001', 'MAGDALENA', 'SANTA MARTA');
INSERT INTO `regions` VALUES ('47', '47030', 'MAGDALENA', 'ALGARROBO');
INSERT INTO `regions` VALUES ('47', '47053', 'MAGDALENA', 'ARACATACA');
INSERT INTO `regions` VALUES ('47', '47058', 'MAGDALENA', 'ARIGUANI');
INSERT INTO `regions` VALUES ('47', '47161', 'MAGDALENA', 'CERRO SAN ANTONIO');
INSERT INTO `regions` VALUES ('47', '47170', 'MAGDALENA', 'CHIVOLO');
INSERT INTO `regions` VALUES ('47', '47189', 'MAGDALENA', 'CIENAGA');
INSERT INTO `regions` VALUES ('47', '47205', 'MAGDALENA', 'CONCORDIA');
INSERT INTO `regions` VALUES ('47', '47245', 'MAGDALENA', 'EL BANCO');
INSERT INTO `regions` VALUES ('47', '47258', 'MAGDALENA', 'EL PIÑON');
INSERT INTO `regions` VALUES ('47', '47268', 'MAGDALENA', 'EL RETEN');
INSERT INTO `regions` VALUES ('47', '47288', 'MAGDALENA', 'FUNDACION');
INSERT INTO `regions` VALUES ('47', '47318', 'MAGDALENA', 'GUAMAL');
INSERT INTO `regions` VALUES ('47', '47460', 'MAGDALENA', 'NUEVA GRANADA');
INSERT INTO `regions` VALUES ('47', '47541', 'MAGDALENA', 'PEDRAZA');
INSERT INTO `regions` VALUES ('47', '47545', 'MAGDALENA', 'PIJIÑO DEL CARMEN');
INSERT INTO `regions` VALUES ('47', '47551', 'MAGDALENA', 'PIVIJAY');
INSERT INTO `regions` VALUES ('47', '47555', 'MAGDALENA', 'PLATO');
INSERT INTO `regions` VALUES ('47', '47570', 'MAGDALENA', 'PUEBLOVIEJO');
INSERT INTO `regions` VALUES ('47', '47605', 'MAGDALENA', 'REMOLINO');
INSERT INTO `regions` VALUES ('47', '47660', 'MAGDALENA', 'SABANAS DE SAN ANGEL');
INSERT INTO `regions` VALUES ('47', '47675', 'MAGDALENA', 'SALAMINA');
INSERT INTO `regions` VALUES ('47', '47692', 'MAGDALENA', 'SAN SEBASTIAN DE BUENAVISTA');
INSERT INTO `regions` VALUES ('47', '47703', 'MAGDALENA', 'SAN ZENON');
INSERT INTO `regions` VALUES ('47', '47707', 'MAGDALENA', 'SANTA ANA');
INSERT INTO `regions` VALUES ('47', '47720', 'MAGDALENA', 'SANTA BARBARA DE PINTO');
INSERT INTO `regions` VALUES ('47', '47745', 'MAGDALENA', 'SITIONUEVO');
INSERT INTO `regions` VALUES ('47', '47798', 'MAGDALENA', 'TENERIFE');
INSERT INTO `regions` VALUES ('47', '47960', 'MAGDALENA', 'ZAPAYAN');
INSERT INTO `regions` VALUES ('47', '47980', 'MAGDALENA', 'ZONA BANANERA');
INSERT INTO `regions` VALUES ('50', '50001', 'META', 'VILLAVICENCIO');
INSERT INTO `regions` VALUES ('50', '50006', 'META', 'ACACIAS');
INSERT INTO `regions` VALUES ('50', '50110', 'META', 'BARRANCA DE UPIA');
INSERT INTO `regions` VALUES ('50', '50124', 'META', 'CABUYARO');
INSERT INTO `regions` VALUES ('50', '50150', 'META', 'CASTILLA LA NUEVA');
INSERT INTO `regions` VALUES ('50', '50223', 'META', 'CUBARRAL');
INSERT INTO `regions` VALUES ('50', '50226', 'META', 'CUMARAL');
INSERT INTO `regions` VALUES ('50', '50245', 'META', 'EL CALVARIO');
INSERT INTO `regions` VALUES ('50', '50251', 'META', 'EL CASTILLO');
INSERT INTO `regions` VALUES ('50', '50270', 'META', 'EL DORADO');
INSERT INTO `regions` VALUES ('50', '50287', 'META', 'FUENTE DE ORO');
INSERT INTO `regions` VALUES ('50', '50313', 'META', 'GRANADA');
INSERT INTO `regions` VALUES ('50', '50318', 'META', 'GUAMAL');
INSERT INTO `regions` VALUES ('50', '50325', 'META', 'MAPIRIPAN');
INSERT INTO `regions` VALUES ('50', '50330', 'META', 'MESETAS');
INSERT INTO `regions` VALUES ('50', '50350', 'META', 'LA MACARENA');
INSERT INTO `regions` VALUES ('50', '50370', 'META', 'LA URIBE');
INSERT INTO `regions` VALUES ('50', '50400', 'META', 'LEJANIAS');
INSERT INTO `regions` VALUES ('50', '50450', 'META', 'PUERTO CONCORDIA');
INSERT INTO `regions` VALUES ('50', '50568', 'META', 'PUERTO GAITAN');
INSERT INTO `regions` VALUES ('50', '50573', 'META', 'PUERTO LOPEZ');
INSERT INTO `regions` VALUES ('50', '50577', 'META', 'PUERTO LLERAS');
INSERT INTO `regions` VALUES ('50', '50590', 'META', 'PUERTO RICO');
INSERT INTO `regions` VALUES ('50', '50606', 'META', 'RESTREPO');
INSERT INTO `regions` VALUES ('50', '50680', 'META', 'SAN CARLOS GUAROA');
INSERT INTO `regions` VALUES ('50', '50683', 'META', 'SAN JUAN DE ARAMA');
INSERT INTO `regions` VALUES ('50', '50686', 'META', 'SAN JUANITO');
INSERT INTO `regions` VALUES ('50', '50689', 'META', 'SAN MARTIN');
INSERT INTO `regions` VALUES ('50', '50711', 'META', 'VISTA HERMOSA');
INSERT INTO `regions` VALUES ('52', '52001', 'NARIÑO', 'PASTO');
INSERT INTO `regions` VALUES ('52', '52019', 'NARIÑO', 'ALBAN');
INSERT INTO `regions` VALUES ('52', '52022', 'NARIÑO', 'ALDANA');
INSERT INTO `regions` VALUES ('52', '52036', 'NARIÑO', 'ANCUYA');
INSERT INTO `regions` VALUES ('52', '52051', 'NARIÑO', 'ARBOLEDA');
INSERT INTO `regions` VALUES ('52', '52079', 'NARIÑO', 'BARBACOAS');
INSERT INTO `regions` VALUES ('52', '52083', 'NARIÑO', 'BELEN');
INSERT INTO `regions` VALUES ('52', '52110', 'NARIÑO', 'BUESACO');
INSERT INTO `regions` VALUES ('52', '52203', 'NARIÑO', 'COLON');
INSERT INTO `regions` VALUES ('52', '52207', 'NARIÑO', 'CONSACA');
INSERT INTO `regions` VALUES ('52', '52210', 'NARIÑO', 'CONTADERO');
INSERT INTO `regions` VALUES ('52', '52215', 'NARIÑO', 'CORDOBA');
INSERT INTO `regions` VALUES ('52', '52224', 'NARIÑO', 'CUASPUD');
INSERT INTO `regions` VALUES ('52', '52227', 'NARIÑO', 'CUMBAL');
INSERT INTO `regions` VALUES ('52', '52233', 'NARIÑO', 'CUMBITARA');
INSERT INTO `regions` VALUES ('52', '52240', 'NARIÑO', 'CHACHAGUI');
INSERT INTO `regions` VALUES ('52', '52250', 'NARIÑO', 'EL CHARCO');
INSERT INTO `regions` VALUES ('52', '52254', 'NARIÑO', 'EL PEÑOL');
INSERT INTO `regions` VALUES ('52', '52256', 'NARIÑO', 'EL ROSARIO');
INSERT INTO `regions` VALUES ('52', '52258', 'NARIÑO', 'EL TABLON DE GOMEZ');
INSERT INTO `regions` VALUES ('52', '52260', 'NARIÑO', 'EL TAMBO');
INSERT INTO `regions` VALUES ('52', '52287', 'NARIÑO', 'FUNES');
INSERT INTO `regions` VALUES ('52', '52317', 'NARIÑO', 'GUACHUCAL');
INSERT INTO `regions` VALUES ('52', '52320', 'NARIÑO', 'GUAITARILLA');
INSERT INTO `regions` VALUES ('52', '52323', 'NARIÑO', 'GUALMATAN');
INSERT INTO `regions` VALUES ('52', '52352', 'NARIÑO', 'ILES');
INSERT INTO `regions` VALUES ('52', '52354', 'NARIÑO', 'IMUES');
INSERT INTO `regions` VALUES ('52', '52356', 'NARIÑO', 'IPIALES');
INSERT INTO `regions` VALUES ('52', '52378', 'NARIÑO', 'LA CRUZ');
INSERT INTO `regions` VALUES ('52', '52381', 'NARIÑO', 'LA FLORIDA');
INSERT INTO `regions` VALUES ('52', '52385', 'NARIÑO', 'LA LLANADA');
INSERT INTO `regions` VALUES ('52', '52390', 'NARIÑO', 'LA TOLA');
INSERT INTO `regions` VALUES ('52', '52399', 'NARIÑO', 'LA UNION');
INSERT INTO `regions` VALUES ('52', '52405', 'NARIÑO', 'LEIVA');
INSERT INTO `regions` VALUES ('52', '52411', 'NARIÑO', 'LINARES');
INSERT INTO `regions` VALUES ('52', '52418', 'NARIÑO', 'LOS ANDES');
INSERT INTO `regions` VALUES ('52', '52427', 'NARIÑO', 'MAGUI');
INSERT INTO `regions` VALUES ('52', '52435', 'NARIÑO', 'MALLAMA');
INSERT INTO `regions` VALUES ('52', '52473', 'NARIÑO', 'MOSQUERA');
INSERT INTO `regions` VALUES ('52', '52480', 'NARIÑO', 'NARIÑO');
INSERT INTO `regions` VALUES ('52', '52490', 'NARIÑO', 'OLAYA HERRERA');
INSERT INTO `regions` VALUES ('52', '52506', 'NARIÑO', 'OSPINA');
INSERT INTO `regions` VALUES ('52', '52520', 'NARIÑO', 'FRANCISCO PIZARRO');
INSERT INTO `regions` VALUES ('52', '52540', 'NARIÑO', 'POLICARPA');
INSERT INTO `regions` VALUES ('52', '52560', 'NARIÑO', 'POTOSI');
INSERT INTO `regions` VALUES ('52', '52565', 'NARIÑO', 'PROVIDENCIA');
INSERT INTO `regions` VALUES ('52', '52573', 'NARIÑO', 'PUERRES');
INSERT INTO `regions` VALUES ('52', '52585', 'NARIÑO', 'PUPIALES');
INSERT INTO `regions` VALUES ('52', '52612', 'NARIÑO', 'RICAURTE');
INSERT INTO `regions` VALUES ('52', '52621', 'NARIÑO', 'ROBERTO PAYAN');
INSERT INTO `regions` VALUES ('52', '52678', 'NARIÑO', 'SAMANIEGO');
INSERT INTO `regions` VALUES ('52', '52683', 'NARIÑO', 'SANDONA');
INSERT INTO `regions` VALUES ('52', '52685', 'NARIÑO', 'SAN BERNARDO');
INSERT INTO `regions` VALUES ('52', '52687', 'NARIÑO', 'SAN LORENZO');
INSERT INTO `regions` VALUES ('52', '52693', 'NARIÑO', 'SAN PABLO');
INSERT INTO `regions` VALUES ('52', '52694', 'NARIÑO', 'SAN PEDRO DE CARTAGO');
INSERT INTO `regions` VALUES ('52', '52696', 'NARIÑO', 'SANTA BARBARA');
INSERT INTO `regions` VALUES ('52', '52699', 'NARIÑO', 'SANTACRUZ');
INSERT INTO `regions` VALUES ('52', '52720', 'NARIÑO', 'SAPUYES');
INSERT INTO `regions` VALUES ('52', '52786', 'NARIÑO', 'TAMINANGO');
INSERT INTO `regions` VALUES ('52', '52788', 'NARIÑO', 'TANGUA');
INSERT INTO `regions` VALUES ('52', '52835', 'NARIÑO', 'TUMACO');
INSERT INTO `regions` VALUES ('52', '52838', 'NARIÑO', 'TUQUERRES');
INSERT INTO `regions` VALUES ('52', '52885', 'NARIÑO', 'YACUANQUER');
INSERT INTO `regions` VALUES ('54', '54001', 'NORTE DE SANTANDER', 'CUCUTA');
INSERT INTO `regions` VALUES ('54', '54003', 'NORTE DE SANTANDER', 'ABREGO');
INSERT INTO `regions` VALUES ('54', '54051', 'NORTE DE SANTANDER', 'ARBOLEDAS');
INSERT INTO `regions` VALUES ('54', '54099', 'NORTE DE SANTANDER', 'BOCHALEMA');
INSERT INTO `regions` VALUES ('54', '54109', 'NORTE DE SANTANDER', 'BUCARASICA');
INSERT INTO `regions` VALUES ('54', '54125', 'NORTE DE SANTANDER', 'CACOTA');
INSERT INTO `regions` VALUES ('54', '54128', 'NORTE DE SANTANDER', 'CACHIRA');
INSERT INTO `regions` VALUES ('54', '54172', 'NORTE DE SANTANDER', 'CHINACOTA');
INSERT INTO `regions` VALUES ('54', '54174', 'NORTE DE SANTANDER', 'CHITAGA');
INSERT INTO `regions` VALUES ('54', '54206', 'NORTE DE SANTANDER', 'CONVENCION');
INSERT INTO `regions` VALUES ('54', '54223', 'NORTE DE SANTANDER', 'CUCUTILLA');
INSERT INTO `regions` VALUES ('54', '54239', 'NORTE DE SANTANDER', 'DURANIA');
INSERT INTO `regions` VALUES ('54', '54245', 'NORTE DE SANTANDER', 'EL CARMEN');
INSERT INTO `regions` VALUES ('54', '54250', 'NORTE DE SANTANDER', 'EL TARRA');
INSERT INTO `regions` VALUES ('54', '54261', 'NORTE DE SANTANDER', 'EL ZULIA');
INSERT INTO `regions` VALUES ('54', '54313', 'NORTE DE SANTANDER', 'GRAMALOTE');
INSERT INTO `regions` VALUES ('54', '54344', 'NORTE DE SANTANDER', 'HACARI');
INSERT INTO `regions` VALUES ('54', '54347', 'NORTE DE SANTANDER', 'HERRAN');
INSERT INTO `regions` VALUES ('54', '54377', 'NORTE DE SANTANDER', 'LABATECA');
INSERT INTO `regions` VALUES ('54', '54385', 'NORTE DE SANTANDER', 'LA ESPERANZA');
INSERT INTO `regions` VALUES ('54', '54398', 'NORTE DE SANTANDER', 'LA PLAYA');
INSERT INTO `regions` VALUES ('54', '54405', 'NORTE DE SANTANDER', 'LOS PATIOS');
INSERT INTO `regions` VALUES ('54', '54418', 'NORTE DE SANTANDER', 'LOURDES');
INSERT INTO `regions` VALUES ('54', '54480', 'NORTE DE SANTANDER', 'MUTISCUA');
INSERT INTO `regions` VALUES ('54', '54498', 'NORTE DE SANTANDER', 'OCAÑA');
INSERT INTO `regions` VALUES ('54', '54518', 'NORTE DE SANTANDER', 'PAMPLONA');
INSERT INTO `regions` VALUES ('54', '54520', 'NORTE DE SANTANDER', 'PAMPLONITA');
INSERT INTO `regions` VALUES ('54', '54553', 'NORTE DE SANTANDER', 'PUERTO SANTANDER');
INSERT INTO `regions` VALUES ('54', '54599', 'NORTE DE SANTANDER', 'RAGONVALIA');
INSERT INTO `regions` VALUES ('54', '54660', 'NORTE DE SANTANDER', 'SALAZAR');
INSERT INTO `regions` VALUES ('54', '54670', 'NORTE DE SANTANDER', 'SAN CALIXTO');
INSERT INTO `regions` VALUES ('54', '54673', 'NORTE DE SANTANDER', 'SAN CAYETANO');
INSERT INTO `regions` VALUES ('54', '54680', 'NORTE DE SANTANDER', 'SANTIAGO');
INSERT INTO `regions` VALUES ('54', '54720', 'NORTE DE SANTANDER', 'SARDINATA');
INSERT INTO `regions` VALUES ('54', '54743', 'NORTE DE SANTANDER', 'SILOS');
INSERT INTO `regions` VALUES ('54', '54800', 'NORTE DE SANTANDER', 'TEORAMA');
INSERT INTO `regions` VALUES ('54', '54810', 'NORTE DE SANTANDER', 'TIBU');
INSERT INTO `regions` VALUES ('54', '54820', 'NORTE DE SANTANDER', 'TOLEDO');
INSERT INTO `regions` VALUES ('54', '54871', 'NORTE DE SANTANDER', 'VILLA CARO');
INSERT INTO `regions` VALUES ('54', '54874', 'NORTE DE SANTANDER', 'VILLA DEL ROSARIO');
INSERT INTO `regions` VALUES ('63', '63001', 'QUINDÍO', 'ARMENIA');
INSERT INTO `regions` VALUES ('63', '63111', 'QUINDÍO', 'BUENAVISTA');
INSERT INTO `regions` VALUES ('63', '63130', 'QUINDÍO', 'CALARCA');
INSERT INTO `regions` VALUES ('63', '63190', 'QUINDÍO', 'CIRCASIA');
INSERT INTO `regions` VALUES ('63', '63212', 'QUINDÍO', 'CORDOBA');
INSERT INTO `regions` VALUES ('63', '63272', 'QUINDÍO', 'FILANDIA');
INSERT INTO `regions` VALUES ('63', '63302', 'QUINDÍO', 'GENOVA');
INSERT INTO `regions` VALUES ('63', '63401', 'QUINDÍO', 'LA TEBAIDA');
INSERT INTO `regions` VALUES ('63', '63470', 'QUINDÍO', 'MONTENEGRO');
INSERT INTO `regions` VALUES ('63', '63548', 'QUINDÍO', 'PIJAO');
INSERT INTO `regions` VALUES ('63', '63594', 'QUINDÍO', 'QUIMBAYA');
INSERT INTO `regions` VALUES ('63', '63690', 'QUINDÍO', 'SALENTO');
INSERT INTO `regions` VALUES ('66', '66001', 'RISARALDA', 'PEREIRA');
INSERT INTO `regions` VALUES ('66', '66045', 'RISARALDA', 'APIA');
INSERT INTO `regions` VALUES ('66', '66075', 'RISARALDA', 'BALBOA');
INSERT INTO `regions` VALUES ('66', '66088', 'RISARALDA', 'BELEN DE UMBRIA');
INSERT INTO `regions` VALUES ('66', '66170', 'RISARALDA', 'DOS QUEBRADAS');
INSERT INTO `regions` VALUES ('66', '66318', 'RISARALDA', 'GUATICA');
INSERT INTO `regions` VALUES ('66', '66383', 'RISARALDA', 'LA CELIA');
INSERT INTO `regions` VALUES ('66', '66400', 'RISARALDA', 'LA VIRGINIA');
INSERT INTO `regions` VALUES ('66', '66440', 'RISARALDA', 'MARSELLA');
INSERT INTO `regions` VALUES ('66', '66456', 'RISARALDA', 'MISTRATO');
INSERT INTO `regions` VALUES ('66', '66572', 'RISARALDA', 'PUEBLO RICO');
INSERT INTO `regions` VALUES ('66', '66594', 'RISARALDA', 'QUINCHIA');
INSERT INTO `regions` VALUES ('66', '66682', 'RISARALDA', 'SANTA ROSA DE CABAL');
INSERT INTO `regions` VALUES ('66', '66687', 'RISARALDA', 'SANTUARIO');
INSERT INTO `regions` VALUES ('68', '68001', 'SANTANDER', 'BUCARAMANGA');
INSERT INTO `regions` VALUES ('68', '68013', 'SANTANDER', 'AGUADA');
INSERT INTO `regions` VALUES ('68', '68020', 'SANTANDER', 'ALBANIA');
INSERT INTO `regions` VALUES ('68', '68051', 'SANTANDER', 'ARATOCA');
INSERT INTO `regions` VALUES ('68', '68077', 'SANTANDER', 'BARBOSA');
INSERT INTO `regions` VALUES ('68', '68079', 'SANTANDER', 'BARICHARA');
INSERT INTO `regions` VALUES ('68', '68081', 'SANTANDER', 'BARRANCABERMEJA');
INSERT INTO `regions` VALUES ('68', '68092', 'SANTANDER', 'BETULIA');
INSERT INTO `regions` VALUES ('68', '68101', 'SANTANDER', 'BOLIVAR');
INSERT INTO `regions` VALUES ('68', '68121', 'SANTANDER', 'CABRERA');
INSERT INTO `regions` VALUES ('68', '68132', 'SANTANDER', 'CALIFORNIA');
INSERT INTO `regions` VALUES ('68', '68147', 'SANTANDER', 'CAPITANEJO');
INSERT INTO `regions` VALUES ('68', '68152', 'SANTANDER', 'CARCASI');
INSERT INTO `regions` VALUES ('68', '68160', 'SANTANDER', 'CEPITA');
INSERT INTO `regions` VALUES ('68', '68162', 'SANTANDER', 'CERRITO');
INSERT INTO `regions` VALUES ('68', '68167', 'SANTANDER', 'CHARALA');
INSERT INTO `regions` VALUES ('68', '68169', 'SANTANDER', 'CHARTA');
INSERT INTO `regions` VALUES ('68', '68176', 'SANTANDER', 'CHIMA');
INSERT INTO `regions` VALUES ('68', '68179', 'SANTANDER', 'CHIPATA');
INSERT INTO `regions` VALUES ('68', '68190', 'SANTANDER', 'CIMITARRA');
INSERT INTO `regions` VALUES ('68', '68207', 'SANTANDER', 'CONCEPCION');
INSERT INTO `regions` VALUES ('68', '68209', 'SANTANDER', 'CONFINES');
INSERT INTO `regions` VALUES ('68', '68211', 'SANTANDER', 'CONTRATACION');
INSERT INTO `regions` VALUES ('68', '68217', 'SANTANDER', 'COROMORO');
INSERT INTO `regions` VALUES ('68', '68229', 'SANTANDER', 'CURITI');
INSERT INTO `regions` VALUES ('68', '68235', 'SANTANDER', 'EL CARMEN DE CHUCURI');
INSERT INTO `regions` VALUES ('68', '68245', 'SANTANDER', 'EL GUACAMAYO');
INSERT INTO `regions` VALUES ('68', '68250', 'SANTANDER', 'EL PEÑON');
INSERT INTO `regions` VALUES ('68', '68255', 'SANTANDER', 'EL PLAYON');
INSERT INTO `regions` VALUES ('68', '68264', 'SANTANDER', 'ENCINO');
INSERT INTO `regions` VALUES ('68', '68266', 'SANTANDER', 'ENCISO');
INSERT INTO `regions` VALUES ('68', '68271', 'SANTANDER', 'FLORIAN');
INSERT INTO `regions` VALUES ('68', '68276', 'SANTANDER', 'FLORIDABLANCA');
INSERT INTO `regions` VALUES ('68', '68296', 'SANTANDER', 'GALAN');
INSERT INTO `regions` VALUES ('68', '68298', 'SANTANDER', 'GAMBITA');
INSERT INTO `regions` VALUES ('68', '68307', 'SANTANDER', 'GIRON');
INSERT INTO `regions` VALUES ('68', '68318', 'SANTANDER', 'GUACA');
INSERT INTO `regions` VALUES ('68', '68320', 'SANTANDER', 'GUADALUPE');
INSERT INTO `regions` VALUES ('68', '68322', 'SANTANDER', 'GUAPOTA');
INSERT INTO `regions` VALUES ('68', '68324', 'SANTANDER', 'GUAVATA');
INSERT INTO `regions` VALUES ('68', '68327', 'SANTANDER', 'GUEPSA');
INSERT INTO `regions` VALUES ('68', '68344', 'SANTANDER', 'HATO');
INSERT INTO `regions` VALUES ('68', '68368', 'SANTANDER', 'JESUS MARIA');
INSERT INTO `regions` VALUES ('68', '68370', 'SANTANDER', 'JORDAN');
INSERT INTO `regions` VALUES ('68', '68377', 'SANTANDER', 'LA BELLEZA');
INSERT INTO `regions` VALUES ('68', '68385', 'SANTANDER', 'LANDAZURI');
INSERT INTO `regions` VALUES ('68', '68397', 'SANTANDER', 'LA PAZ');
INSERT INTO `regions` VALUES ('68', '68406', 'SANTANDER', 'LEBRIJA');
INSERT INTO `regions` VALUES ('68', '68418', 'SANTANDER', 'LOS SANTOS');
INSERT INTO `regions` VALUES ('68', '68425', 'SANTANDER', 'MACARAVITA');
INSERT INTO `regions` VALUES ('68', '68432', 'SANTANDER', 'MALAGA');
INSERT INTO `regions` VALUES ('68', '68444', 'SANTANDER', 'MATANZA');
INSERT INTO `regions` VALUES ('68', '68464', 'SANTANDER', 'MOGOTES');
INSERT INTO `regions` VALUES ('68', '68468', 'SANTANDER', 'MOLAGAVITA');
INSERT INTO `regions` VALUES ('68', '68498', 'SANTANDER', 'OCAMONTE');
INSERT INTO `regions` VALUES ('68', '68500', 'SANTANDER', 'OIBA');
INSERT INTO `regions` VALUES ('68', '68502', 'SANTANDER', 'ONZAGA');
INSERT INTO `regions` VALUES ('68', '68522', 'SANTANDER', 'PALMAR');
INSERT INTO `regions` VALUES ('68', '68524', 'SANTANDER', 'PALMAS DEL SOCORRO');
INSERT INTO `regions` VALUES ('68', '68533', 'SANTANDER', 'PARAMO');
INSERT INTO `regions` VALUES ('68', '68547', 'SANTANDER', 'PIEDECUESTA');
INSERT INTO `regions` VALUES ('68', '68549', 'SANTANDER', 'PINCHOTE');
INSERT INTO `regions` VALUES ('68', '68572', 'SANTANDER', 'PUENTE NACIONAL');
INSERT INTO `regions` VALUES ('68', '68573', 'SANTANDER', 'PUERTO PARRA');
INSERT INTO `regions` VALUES ('68', '68575', 'SANTANDER', 'PUERTO WILCHES');
INSERT INTO `regions` VALUES ('68', '68615', 'SANTANDER', 'RIONEGRO');
INSERT INTO `regions` VALUES ('68', '68655', 'SANTANDER', 'SABANA DE TORRES');
INSERT INTO `regions` VALUES ('68', '68669', 'SANTANDER', 'SAN ANDRES');
INSERT INTO `regions` VALUES ('68', '68673', 'SANTANDER', 'SAN BENITO');
INSERT INTO `regions` VALUES ('68', '68679', 'SANTANDER', 'SAN GIL');
INSERT INTO `regions` VALUES ('68', '68682', 'SANTANDER', 'SAN JOAQUIN');
INSERT INTO `regions` VALUES ('68', '68684', 'SANTANDER', 'SAN JOSE DE MIRANDA');
INSERT INTO `regions` VALUES ('68', '68686', 'SANTANDER', 'SAN MIGUEL');
INSERT INTO `regions` VALUES ('68', '68689', 'SANTANDER', 'SAN VICENTE DE CHUCURI');
INSERT INTO `regions` VALUES ('68', '68705', 'SANTANDER', 'SANTA BARBARA');
INSERT INTO `regions` VALUES ('68', '68720', 'SANTANDER', 'SANTA HELENA DEL OPON');
INSERT INTO `regions` VALUES ('68', '68745', 'SANTANDER', 'SIMACOTA');
INSERT INTO `regions` VALUES ('68', '68755', 'SANTANDER', 'SOCORRO');
INSERT INTO `regions` VALUES ('68', '68770', 'SANTANDER', 'SUAITA');
INSERT INTO `regions` VALUES ('68', '68773', 'SANTANDER', 'SUCRE');
INSERT INTO `regions` VALUES ('68', '68780', 'SANTANDER', 'SURATA');
INSERT INTO `regions` VALUES ('68', '68820', 'SANTANDER', 'TONA');
INSERT INTO `regions` VALUES ('68', '68855', 'SANTANDER', 'VALLE DE SAN JOSE');
INSERT INTO `regions` VALUES ('68', '68861', 'SANTANDER', 'VELEZ');
INSERT INTO `regions` VALUES ('68', '68867', 'SANTANDER', 'VETAS');
INSERT INTO `regions` VALUES ('68', '68872', 'SANTANDER', 'VILLANUEVA');
INSERT INTO `regions` VALUES ('68', '68895', 'SANTANDER', 'ZAPATOCA');
INSERT INTO `regions` VALUES ('70', '70001', 'SUCRE', 'SINCELEJO');
INSERT INTO `regions` VALUES ('70', '70110', 'SUCRE', 'BUENAVISTA');
INSERT INTO `regions` VALUES ('70', '70124', 'SUCRE', 'CAIMITO');
INSERT INTO `regions` VALUES ('70', '70204', 'SUCRE', 'COLOSO');
INSERT INTO `regions` VALUES ('70', '70215', 'SUCRE', 'COROZAL');
INSERT INTO `regions` VALUES ('70', '70221', 'SUCRE', 'COVEÑAS');
INSERT INTO `regions` VALUES ('70', '70230', 'SUCRE', 'CHALAN');
INSERT INTO `regions` VALUES ('70', '70233', 'SUCRE', 'EL ROBLE');
INSERT INTO `regions` VALUES ('70', '70235', 'SUCRE', 'GALERAS');
INSERT INTO `regions` VALUES ('70', '70265', 'SUCRE', 'GUARANDA');
INSERT INTO `regions` VALUES ('70', '70400', 'SUCRE', 'LA UNION');
INSERT INTO `regions` VALUES ('70', '70418', 'SUCRE', 'LOS PALMITOS');
INSERT INTO `regions` VALUES ('70', '70429', 'SUCRE', 'MAJAGUAL');
INSERT INTO `regions` VALUES ('70', '70473', 'SUCRE', 'MORROA');
INSERT INTO `regions` VALUES ('70', '70508', 'SUCRE', 'OVEJAS');
INSERT INTO `regions` VALUES ('70', '70523', 'SUCRE', 'PALMITO');
INSERT INTO `regions` VALUES ('70', '70670', 'SUCRE', 'SAMPUES');
INSERT INTO `regions` VALUES ('70', '70678', 'SUCRE', 'SAN BENITO ABAD');
INSERT INTO `regions` VALUES ('70', '70702', 'SUCRE', 'SAN JUAN BETULIA');
INSERT INTO `regions` VALUES ('70', '70708', 'SUCRE', 'SAN MARCOS');
INSERT INTO `regions` VALUES ('70', '70713', 'SUCRE', 'SAN ONOFRE');
INSERT INTO `regions` VALUES ('70', '70717', 'SUCRE', 'SAN PEDRO');
INSERT INTO `regions` VALUES ('70', '70742', 'SUCRE', 'SINCE');
INSERT INTO `regions` VALUES ('70', '70771', 'SUCRE', 'SUCRE');
INSERT INTO `regions` VALUES ('70', '70820', 'SUCRE', 'SANTIAGO DE TOLU');
INSERT INTO `regions` VALUES ('70', '70823', 'SUCRE', 'TOLU VIEJO');
INSERT INTO `regions` VALUES ('73', '73001', 'TOLIMA', 'IBAGUE');
INSERT INTO `regions` VALUES ('73', '73024', 'TOLIMA', 'ALPUJARRA');
INSERT INTO `regions` VALUES ('73', '73026', 'TOLIMA', 'ALVARADO');
INSERT INTO `regions` VALUES ('73', '73030', 'TOLIMA', 'AMBALEMA');
INSERT INTO `regions` VALUES ('73', '73043', 'TOLIMA', 'ANZOATEGUI');
INSERT INTO `regions` VALUES ('73', '73055', 'TOLIMA', 'ARMERO GUAYABAL');
INSERT INTO `regions` VALUES ('73', '73067', 'TOLIMA', 'ATACO');
INSERT INTO `regions` VALUES ('73', '73124', 'TOLIMA', 'CAJAMARCA');
INSERT INTO `regions` VALUES ('73', '73148', 'TOLIMA', 'CARMEN DE APICALA');
INSERT INTO `regions` VALUES ('73', '73152', 'TOLIMA', 'CASABIANCA');
INSERT INTO `regions` VALUES ('73', '73168', 'TOLIMA', 'CHAPARRAL');
INSERT INTO `regions` VALUES ('73', '73200', 'TOLIMA', 'COELLO');
INSERT INTO `regions` VALUES ('73', '73217', 'TOLIMA', 'COYAIMA');
INSERT INTO `regions` VALUES ('73', '73226', 'TOLIMA', 'CUNDAY');
INSERT INTO `regions` VALUES ('73', '73236', 'TOLIMA', 'DOLORES');
INSERT INTO `regions` VALUES ('73', '73268', 'TOLIMA', 'ESPINAL');
INSERT INTO `regions` VALUES ('73', '73270', 'TOLIMA', 'FALAN');
INSERT INTO `regions` VALUES ('73', '73275', 'TOLIMA', 'FLANDES');
INSERT INTO `regions` VALUES ('73', '73283', 'TOLIMA', 'FRESNO');
INSERT INTO `regions` VALUES ('73', '73319', 'TOLIMA', 'GUAMO');
INSERT INTO `regions` VALUES ('73', '73347', 'TOLIMA', 'HERVEO');
INSERT INTO `regions` VALUES ('73', '73349', 'TOLIMA', 'HONDA');
INSERT INTO `regions` VALUES ('73', '73352', 'TOLIMA', 'ICONONZO');
INSERT INTO `regions` VALUES ('73', '73408', 'TOLIMA', 'LERIDA');
INSERT INTO `regions` VALUES ('73', '73411', 'TOLIMA', 'LIBANO');
INSERT INTO `regions` VALUES ('73', '73443', 'TOLIMA', 'MARIQUITA');
INSERT INTO `regions` VALUES ('73', '73449', 'TOLIMA', 'MELGAR');
INSERT INTO `regions` VALUES ('73', '73461', 'TOLIMA', 'MURILLO');
INSERT INTO `regions` VALUES ('73', '73483', 'TOLIMA', 'NATAGAIMA');
INSERT INTO `regions` VALUES ('73', '73504', 'TOLIMA', 'ORTEGA');
INSERT INTO `regions` VALUES ('73', '73520', 'TOLIMA', 'PALOCABILDO');
INSERT INTO `regions` VALUES ('73', '73547', 'TOLIMA', 'PIEDRAS');
INSERT INTO `regions` VALUES ('73', '73555', 'TOLIMA', 'PLANADAS');
INSERT INTO `regions` VALUES ('73', '73563', 'TOLIMA', 'PRADO');
INSERT INTO `regions` VALUES ('73', '73585', 'TOLIMA', 'PURIFICACION');
INSERT INTO `regions` VALUES ('73', '73616', 'TOLIMA', 'RIOBLANCO');
INSERT INTO `regions` VALUES ('73', '73622', 'TOLIMA', 'RONCESVALLES');
INSERT INTO `regions` VALUES ('73', '73624', 'TOLIMA', 'ROVIRA');
INSERT INTO `regions` VALUES ('73', '73671', 'TOLIMA', 'SALDAÑA');
INSERT INTO `regions` VALUES ('73', '73675', 'TOLIMA', 'SAN ANTONIO');
INSERT INTO `regions` VALUES ('73', '73678', 'TOLIMA', 'SAN LUIS');
INSERT INTO `regions` VALUES ('73', '73686', 'TOLIMA', 'SANTA ISABEL');
INSERT INTO `regions` VALUES ('73', '73770', 'TOLIMA', 'SUAREZ');
INSERT INTO `regions` VALUES ('73', '73854', 'TOLIMA', 'VALLE DE SAN JUAN');
INSERT INTO `regions` VALUES ('73', '73861', 'TOLIMA', 'VENADILLO');
INSERT INTO `regions` VALUES ('73', '73870', 'TOLIMA', 'VILLAHERMOSA');
INSERT INTO `regions` VALUES ('73', '73873', 'TOLIMA', 'VILLARRICA');
INSERT INTO `regions` VALUES ('76', '76001', 'VALLE DEL CAUCA', 'CALI');
INSERT INTO `regions` VALUES ('76', '76020', 'VALLE DEL CAUCA', 'ALCALA');
INSERT INTO `regions` VALUES ('76', '76036', 'VALLE DEL CAUCA', 'ANDALUCIA');
INSERT INTO `regions` VALUES ('76', '76041', 'VALLE DEL CAUCA', 'ANSERMANUEVO');
INSERT INTO `regions` VALUES ('76', '76054', 'VALLE DEL CAUCA', 'ARGELIA');
INSERT INTO `regions` VALUES ('76', '76100', 'VALLE DEL CAUCA', 'BOLIVAR');
INSERT INTO `regions` VALUES ('76', '76109', 'VALLE DEL CAUCA', 'BUENAVENTURA');
INSERT INTO `regions` VALUES ('76', '76111', 'VALLE DEL CAUCA', 'BUGA');
INSERT INTO `regions` VALUES ('76', '76113', 'VALLE DEL CAUCA', 'BUGALAGRANDE');
INSERT INTO `regions` VALUES ('76', '76122', 'VALLE DEL CAUCA', 'CAICEDONIA');
INSERT INTO `regions` VALUES ('76', '76126', 'VALLE DEL CAUCA', 'CALIMA');
INSERT INTO `regions` VALUES ('76', '76130', 'VALLE DEL CAUCA', 'CANDELARIA');
INSERT INTO `regions` VALUES ('76', '76147', 'VALLE DEL CAUCA', 'CARTAGO');
INSERT INTO `regions` VALUES ('76', '76233', 'VALLE DEL CAUCA', 'DAGUA');
INSERT INTO `regions` VALUES ('76', '76243', 'VALLE DEL CAUCA', 'EL AGUILA');
INSERT INTO `regions` VALUES ('76', '76246', 'VALLE DEL CAUCA', 'EL CAIRO');
INSERT INTO `regions` VALUES ('76', '76248', 'VALLE DEL CAUCA', 'EL CERRITO');
INSERT INTO `regions` VALUES ('76', '76250', 'VALLE DEL CAUCA', 'EL DOVIO');
INSERT INTO `regions` VALUES ('76', '76275', 'VALLE DEL CAUCA', 'FLORIDA');
INSERT INTO `regions` VALUES ('76', '76306', 'VALLE DEL CAUCA', 'GINEBRA');
INSERT INTO `regions` VALUES ('76', '76318', 'VALLE DEL CAUCA', 'GUACARI');
INSERT INTO `regions` VALUES ('76', '76364', 'VALLE DEL CAUCA', 'JAMUNDI');
INSERT INTO `regions` VALUES ('76', '76377', 'VALLE DEL CAUCA', 'LA CUMBRE');
INSERT INTO `regions` VALUES ('76', '76400', 'VALLE DEL CAUCA', 'LA UNION');
INSERT INTO `regions` VALUES ('76', '76403', 'VALLE DEL CAUCA', 'LA VICTORIA');
INSERT INTO `regions` VALUES ('76', '76497', 'VALLE DEL CAUCA', 'OBANDO');
INSERT INTO `regions` VALUES ('76', '76520', 'VALLE DEL CAUCA', 'PALMIRA');
INSERT INTO `regions` VALUES ('76', '76563', 'VALLE DEL CAUCA', 'PRADERA');
INSERT INTO `regions` VALUES ('76', '76606', 'VALLE DEL CAUCA', 'RESTREPO');
INSERT INTO `regions` VALUES ('76', '76616', 'VALLE DEL CAUCA', 'RIOFRIO');
INSERT INTO `regions` VALUES ('76', '76622', 'VALLE DEL CAUCA', 'ROLDANILLO');
INSERT INTO `regions` VALUES ('76', '76670', 'VALLE DEL CAUCA', 'SAN PEDRO');
INSERT INTO `regions` VALUES ('76', '76736', 'VALLE DEL CAUCA', 'SEVILLA');
INSERT INTO `regions` VALUES ('76', '76823', 'VALLE DEL CAUCA', 'TORO');
INSERT INTO `regions` VALUES ('76', '76828', 'VALLE DEL CAUCA', 'TRUJILLO');
INSERT INTO `regions` VALUES ('76', '76834', 'VALLE DEL CAUCA', 'TULUA');
INSERT INTO `regions` VALUES ('76', '76845', 'VALLE DEL CAUCA', 'ULLOA');
INSERT INTO `regions` VALUES ('76', '76863', 'VALLE DEL CAUCA', 'VERSALLES');
INSERT INTO `regions` VALUES ('76', '76869', 'VALLE DEL CAUCA', 'VIJES');
INSERT INTO `regions` VALUES ('76', '76890', 'VALLE DEL CAUCA', 'YOTOCO');
INSERT INTO `regions` VALUES ('76', '76892', 'VALLE DEL CAUCA', 'YUMBO');
INSERT INTO `regions` VALUES ('76', '76895', 'VALLE DEL CAUCA', 'ZARZAL');
INSERT INTO `regions` VALUES ('81', '81001', 'ARAUCA', 'ARAUCA');
INSERT INTO `regions` VALUES ('81', '81065', 'ARAUCA', 'ARAUQUITA');
INSERT INTO `regions` VALUES ('81', '81220', 'ARAUCA', 'CRAVO NORTE');
INSERT INTO `regions` VALUES ('81', '81300', 'ARAUCA', 'FORTUL');
INSERT INTO `regions` VALUES ('81', '81591', 'ARAUCA', 'PUERTO RONDON');
INSERT INTO `regions` VALUES ('81', '81736', 'ARAUCA', 'SARAVENA');
INSERT INTO `regions` VALUES ('81', '81794', 'ARAUCA', 'TAME');
INSERT INTO `regions` VALUES ('85', '85001', 'CASANARE', 'YOPAL');
INSERT INTO `regions` VALUES ('85', '85010', 'CASANARE', 'AGUAZUL');
INSERT INTO `regions` VALUES ('85', '85015', 'CASANARE', 'CHAMEZA');
INSERT INTO `regions` VALUES ('85', '85125', 'CASANARE', 'HATO COROZAL');
INSERT INTO `regions` VALUES ('85', '85136', 'CASANARE', 'LA SALINA');
INSERT INTO `regions` VALUES ('85', '85139', 'CASANARE', 'MANI');
INSERT INTO `regions` VALUES ('85', '85162', 'CASANARE', 'MONTERREY');
INSERT INTO `regions` VALUES ('85', '85225', 'CASANARE', 'NUNCHIA');
INSERT INTO `regions` VALUES ('85', '85230', 'CASANARE', 'OROCUE');
INSERT INTO `regions` VALUES ('85', '85250', 'CASANARE', 'PAZ DE ARIPORO');
INSERT INTO `regions` VALUES ('85', '85263', 'CASANARE', 'PORE');
INSERT INTO `regions` VALUES ('85', '85279', 'CASANARE', 'RECETOR');
INSERT INTO `regions` VALUES ('85', '85300', 'CASANARE', 'SABANALARGA');
INSERT INTO `regions` VALUES ('85', '85315', 'CASANARE', 'SACAMA');
INSERT INTO `regions` VALUES ('85', '85325', 'CASANARE', 'SAN LUIS DE PALENQUE');
INSERT INTO `regions` VALUES ('85', '85400', 'CASANARE', 'TAMARA');
INSERT INTO `regions` VALUES ('85', '85410', 'CASANARE', 'TAURAMENA');
INSERT INTO `regions` VALUES ('85', '85430', 'CASANARE', 'TRINIDAD');
INSERT INTO `regions` VALUES ('85', '85440', 'CASANARE', 'VILLANUEVA');
INSERT INTO `regions` VALUES ('86', '86001', 'PUTUMAYO', 'MOCOA');
INSERT INTO `regions` VALUES ('86', '86219', 'PUTUMAYO', 'COLON');
INSERT INTO `regions` VALUES ('86', '86320', 'PUTUMAYO', 'ORITO');
INSERT INTO `regions` VALUES ('86', '86568', 'PUTUMAYO', 'PUERTO ASIS');
INSERT INTO `regions` VALUES ('86', '86569', 'PUTUMAYO', 'PUERTO CAICEDO');
INSERT INTO `regions` VALUES ('86', '86571', 'PUTUMAYO', 'PUERTO GUZMAN');
INSERT INTO `regions` VALUES ('86', '86573', 'PUTUMAYO', 'LEGUIZAMO');
INSERT INTO `regions` VALUES ('86', '86749', 'PUTUMAYO', 'SIBUNDOY');
INSERT INTO `regions` VALUES ('86', '86755', 'PUTUMAYO', 'SAN FRANCISCO');
INSERT INTO `regions` VALUES ('86', '86757', 'PUTUMAYO', 'SAN MIGUEL');
INSERT INTO `regions` VALUES ('86', '86760', 'PUTUMAYO', 'SANTIAGO');
INSERT INTO `regions` VALUES ('86', '86865', 'PUTUMAYO', 'VALLE DEL GUAMUEZ');
INSERT INTO `regions` VALUES ('86', '86885', 'PUTUMAYO', 'VILLAGARZON');
INSERT INTO `regions` VALUES ('88', '88001', 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y ', 'SAN ANDRES');
INSERT INTO `regions` VALUES ('88', '88564', 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y ', 'PROVIDENCIA');
INSERT INTO `regions` VALUES ('91', '91001', 'AMAZONAS', 'LETICIA');
INSERT INTO `regions` VALUES ('91', '91263', 'AMAZONAS', 'EL ENCANTO');
INSERT INTO `regions` VALUES ('91', '91405', 'AMAZONAS', 'LA CHORRERA');
INSERT INTO `regions` VALUES ('91', '91407', 'AMAZONAS', 'LA PEDRERA');
INSERT INTO `regions` VALUES ('91', '91430', 'AMAZONAS', 'LA VICTORIA');
INSERT INTO `regions` VALUES ('91', '91460', 'AMAZONAS', 'MIRITI - PARANA');
INSERT INTO `regions` VALUES ('91', '91530', 'AMAZONAS', 'PUERTO ALEGRIA');
INSERT INTO `regions` VALUES ('91', '91536', 'AMAZONAS', 'PUERTO ARICA');
INSERT INTO `regions` VALUES ('91', '91540', 'AMAZONAS', 'PUERTO NARIÑO');
INSERT INTO `regions` VALUES ('91', '91669', 'AMAZONAS', 'PUERTO SANTANDER');
INSERT INTO `regions` VALUES ('91', '91798', 'AMAZONAS', 'TARAPACA');
INSERT INTO `regions` VALUES ('94', '94001', 'GUAINÍA', 'INIRIDA');
INSERT INTO `regions` VALUES ('94', '94343', 'GUAINÍA', 'BARRANCO MINA');
INSERT INTO `regions` VALUES ('94', '94663', 'GUAINÍA', 'MAPIRIPANA');
INSERT INTO `regions` VALUES ('94', '94883', 'GUAINÍA', 'SAN FELIPE');
INSERT INTO `regions` VALUES ('94', '94884', 'GUAINÍA', 'PUERTO COLOMBIA');
INSERT INTO `regions` VALUES ('94', '94885', 'GUAINÍA', 'LA GUADALUPE');
INSERT INTO `regions` VALUES ('94', '94886', 'GUAINÍA', 'CACAHUAL');
INSERT INTO `regions` VALUES ('94', '94887', 'GUAINÍA', 'PANA PANA');
INSERT INTO `regions` VALUES ('94', '94888', 'GUAINÍA', 'MORICHAL');
INSERT INTO `regions` VALUES ('95', '95001', 'GUAVIARE', 'SAN JOSE DEL GUAVIARE');
INSERT INTO `regions` VALUES ('95', '95015', 'GUAVIARE', 'CALAMAR');
INSERT INTO `regions` VALUES ('95', '95025', 'GUAVIARE', 'EL RETORNO');
INSERT INTO `regions` VALUES ('95', '95200', 'GUAVIARE', 'MIRAFLORES');
INSERT INTO `regions` VALUES ('97', '97001', 'VAUPÉS', 'MITU');
INSERT INTO `regions` VALUES ('97', '97161', 'VAUPÉS', 'CARURU');
INSERT INTO `regions` VALUES ('97', '97511', 'VAUPÉS', 'PACOA');
INSERT INTO `regions` VALUES ('97', '97666', 'VAUPÉS', 'TARAIRA');
INSERT INTO `regions` VALUES ('97', '97777', 'VAUPÉS', 'PAPUNAHUA');
INSERT INTO `regions` VALUES ('97', '97889', 'VAUPÉS', 'YAVARATE');
INSERT INTO `regions` VALUES ('99', '99001', 'VICHADA', 'PUERTO CARREÑO');
INSERT INTO `regions` VALUES ('99', '99524', 'VICHADA', 'LA PRIMAVERA');
INSERT INTO `regions` VALUES ('99', '99624', 'VICHADA', 'SANTA ROSALIA');
INSERT INTO `regions` VALUES ('99', '99773', 'VICHADA', 'CUMARIBO');

-- ----------------------------
-- Table structure for states
-- ----------------------------
DROP TABLE IF EXISTS `states`;
CREATE TABLE `states` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created` datetime NOT NULL,
  `createdby` int(11) NOT NULL,
  `modified` datetime DEFAULT NULL,
  `modifiedby` int(11) DEFAULT NULL,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of states
-- ----------------------------
INSERT INTO `states` VALUES ('1', 'Abierto', '2014-08-02 17:45:08', '1', null, null, '0');
INSERT INTO `states` VALUES ('2', 'En proceso', '2014-08-02 17:45:49', '1', null, null, '0');
INSERT INTO `states` VALUES ('3', 'Cerrado', '2014-08-02 17:45:52', '1', null, null, '0');
INSERT INTO `states` VALUES ('4', 'Remitido a otra Entidad', '2014-08-02 17:45:54', '1', null, null, '0');

-- ----------------------------
-- Table structure for subtipologies
-- ----------------------------
DROP TABLE IF EXISTS `subtipologies`;
CREATE TABLE `subtipologies` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tipology_id` int(11) NOT NULL,
  `name` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created` datetime NOT NULL,
  `createdby` int(11) NOT NULL,
  `modified` datetime DEFAULT NULL,
  `modifiedby` int(11) DEFAULT NULL,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `tipology_id` (`tipology_id`),
  CONSTRAINT `subtipologies_ibfk_1` FOREIGN KEY (`tipology_id`) REFERENCES `tipologies` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of subtipologies
-- ----------------------------
INSERT INTO `subtipologies` VALUES ('1', '1', 'No hay atención', '2014-08-03 00:33:35', '1', null, null, '0');
INSERT INTO `subtipologies` VALUES ('2', '1', 'Maltrato', '2014-08-03 01:58:15', '1', null, null, '0');
INSERT INTO `subtipologies` VALUES ('3', '1', 'Neglligencia', '2014-08-03 01:58:32', '1', null, null, '0');

-- ----------------------------
-- Table structure for tipologies
-- ----------------------------
DROP TABLE IF EXISTS `tipologies`;
CREATE TABLE `tipologies` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created` datetime NOT NULL,
  `createdby` int(11) NOT NULL,
  `modified` datetime DEFAULT NULL,
  `modifiedby` int(11) DEFAULT NULL,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of tipologies
-- ----------------------------
INSERT INTO `tipologies` VALUES ('1', 'Salud', '2014-08-03 00:33:04', '1', null, null, '0');
INSERT INTO `tipologies` VALUES ('2', 'Estudio', '2014-08-03 01:57:49', '1', null, null, '0');
INSERT INTO `tipologies` VALUES ('3', 'Habitat', '2014-08-03 01:57:46', '1', null, null, '0');

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `group_id` int(11) NOT NULL,
  `username` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `document` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `phone` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created` datetime NOT NULL,
  `createdby` int(11) NOT NULL,
  `modified` datetime DEFAULT NULL,
  `modifiedby` int(11) DEFAULT NULL,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `group_id` (`group_id`),
  CONSTRAINT `users_ibfk_1` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES ('1', '1', 'funcionario', '$2a$10$7V87bBu7Z8T5KecpYDU3luzASuvl.zWtpPj9GZ34Ej64wdukkUSti', '1010', 'lucerovivas@gmail.com', '3218322323', '2014-08-02 17:43:36', '1', null, null, '0');
INSERT INTO `users` VALUES ('2', '2', '1018408050', '$2a$10$7V87bBu7Z8T5KecpYDU3luzASuvl.zWtpPj9GZ34Ej64wdukkUSti', '1018', 'asa@gmail.com', '3216574848', '2014-08-02 17:44:35', '1', null, null, '0');
INSERT INTO `users` VALUES ('3', '2', '1010188564', '$2a$10$7V87bBu7Z8T5KecpYDU3luzASuvl.zWtpPj9GZ34Ej64wdukkUSti', '1010188', 'asad@sads.com', '3214555555', '2014-08-02 20:26:22', '1', null, null, '0');
INSERT INTO `users` VALUES ('6', '2', '10102332423', '$2a$10$Pa2/EGMbBwaKQl4z0CU/Les9H0bp89y5SU9ucHsjsAcQ8p4gnCdse', '10102332423', 'luu@gmail.com', '3214328749', '2014-08-02 17:43:36', '1', '2014-08-02 17:43:36', '1', '0');
INSERT INTO `users` VALUES ('7', '2', '1010233242322', '$2a$10$AvRMNon88C6cic8msOkVIujp/ymO4KFD0AgnJklmstG/z9437JmIu', '1010233242322', 'luu@gmail.com', '3214328749', '2014-08-02 17:43:36', '1', '2014-08-02 17:43:36', '1', '0');
INSERT INTO `users` VALUES ('8', '2', '23423', '$2a$10$IpbUWh8tgnVlPAMrJdxa.OKtCimxPwfDyCLzWEdKPSdUFDB6VXkkO', '23423', 'luu@gmail.com', '3214328749', '2014-08-02 17:43:36', '1', '2014-08-03 03:25:50', null, '0');
INSERT INTO `users` VALUES ('9', '2', '2342333', '$2a$10$/hnk0dMDgG83b0ljzg1qkO483fjZ5iih1P./YCFev8AlgXEnbnFKK', '2342333', 'luu@gmail.com', '3214328749', '2014-08-02 17:43:36', '1', '2014-08-03 03:35:26', null, '0');
